### ISSUE TITLE
[Bug] 章节名称重复的情况下，导出本章标注会默认导出前一个同名章节内的内容

### ISSUE THREAD

**Issue by Anti11211** [Higurashi-kagome/wereader#103]
**扩展是否为最新版本（与[扩展商店](https://chrome.google.com/webstore/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/cmlenojlebcodibpdhmklglnbaghpdcg?hl=zh-CN&authuser=0)中的版本相同）**

- [x] 是

**出现该问题的书本及章节（不方便公开的话可直接发[邮箱](mailto:higurashi-kagome@qq.com)告知）**
《置身事内：中国政府与经济发展》中每一章的最后两小节“结语”和“扩展阅读”
**描述问题**

对所有章节中“结语”和“扩展阅读”这两小节采用导出本章标注操作，导出的都是第一章中“结语”和“扩展阅读”的内容，也就是说，无法区分同名章节的内容
**复现步骤**

1.打开《置身事内：中国政府与经济发展》第一章的“结语”章节，作出标注A，利用本扩展“获取标注-本章”功能，导出内容a
2.打开《置身事内：中国政府与经济发展》第二章的“结语”章节，作出标注B，利用本扩展“获取标注-本章”功能，导出内容依旧为内容a
3.实验后发现，之后的每一个同名章节，导出内容都是内容a
**期待的正常行为**

**截图**

**额外信息**

**Comment by Higurashi-kagome** [comment]
嗯，确实有这个问题。会尝试在下次更新中修复。
