### ISSUE TITLE
[Feature] 提取当前阅读书籍的作者、书名等

### ISSUE THREAD

**Issue by jingfanglearning** [Higurashi-kagome/wereader#104]
**请描述目前使用微信读书笔记助手遇到什么不便**

很多学者会有这样的需求：在微信阅读当中阅读多本书籍，这就需要注明阅读的来源出处，如果在阅读的时候回头去看书籍名称，作者，出版社，还要慢慢一个字一个字打出来，打断阅读流程

**理想情况下，笔记助手应该怎么做**

我正在阅读一本书，然后能够用插件提取当前书籍的元数据，格式可以按照论文参考文献：[1] 张仲景.伤寒论[M.北京: 中医古籍出版社，1997:6
谢谢！

**额外信息**

**Comment by Higurashi-kagome** [comment]
v2.26.0已提交审核，支持导出书本信息。不过微信读书的书本信息中好像没有“专著”、“报刊”这种分类，好像也没有出版地。所以导出的内容可能需要额外补充。

帮助信息中给出了一个接近论文参考格式的模板，可以使用这个模板试试。

<details>
<summary>Details</summary>

![image](https://github.com/Higurashi-kagome/wereader/assets/51501079/eab32aa2-921a-4139-a75f-08c5e2057b01)

</details>
