### ISSUE TITLE
[Feature] 当标记的文本里有两个想法时，导出时会重复标记的文本

### ISSUE THREAD

**Issue by dongrentianyu** [Higurashi-kagome/wereader#105]
**请描述目前使用微信读书笔记助手遇到什么不便**

标记一处文本，并添加想法。再添加一次想法。然后会导出重复的标记文本。

![image](https://github.com/Higurashi-kagome/wereader/assets/109711900/9b63e5a4-44ad-4929-b604-6f0c607f1d4c)

如上图所示。 

**理想情况下，笔记助手应该怎么做**

可以做成可勾选的状态。是否去除重复标记文本。

**额外信息**

这个功能还是挺需要的，因为一本书会重复阅读几次，每次看到时都可能产生不同的想法。而微信读书又没有搞继续编辑原来的想法的功能。导致每次添加新想法，不是附加到原来想法中，而是生成新的。

但还是要狠狠夸赞一下，这个插件做得实在太好了，能解决很多问题。

**Comment by Higurashi-kagome** [comment]
可以试试这个：

![image](https://github.com/Higurashi-kagome/wereader/assets/51501079/53865de9-9042-41e9-94af-d3fa7cda8c91)

**Comment by dongrentianyu** [comment]
这些都试过了，还是会有重复的文本。因为是一个文本里有两个想法，所以就会是文本重复，但想法不重复，而出现上面图示的情况。

**Comment by Higurashi-kagome** [comment]
哦，我没仔细看。下次更新时会修复这个问题。

**Comment by Higurashi-kagome** [comment]
v2.16.0已更新到 Chrome，Edge 还在审核。添加了一个选项来处理这种情况，可以试试：

<details>
<summary>Details</summary>

![image](https://github.com/Higurashi-kagome/wereader/assets/51501079/2be375de-a8ca-437e-9375-5bc13cebd00c)

</details>

**Comment by dongrentianyu** [comment]
原来是v2.26.0版本，我还以为是版本号出错了。

**Comment by Higurashi-kagome** [comment]
嗯，是，版本是 v2.26.0。

**Comment by dongrentianyu** [comment]
差不多实现了。但从想法那边导出内容还是会重复。用导出标记就不会重复了。

**Comment by Higurashi-kagome** [comment]
我这里看好像是正常的。标记一条文本，添加两条想法，选择“保留想法所对应文本”，只导出了一次内容：

![image](https://github.com/Higurashi-kagome/wereader/assets/51501079/8c720555-5d3f-47af-8bbf-e593191790a7)

**Comment by dongrentianyu** [comment]
对，导出标记时没问题。但如果导出的时候选择导出想法，就会出现重复了。

![image](https://github.com/Higurashi-kagome/wereader/assets/109711900/15aece73-ceef-41b1-8d06-670e68ea65e8)

不过还是非常感谢你。已经够用了。

**Comment by Higurashi-kagome** [comment]
嗯，我明白了。下次更新会补充完善这个。
