### ISSUE TITLE
不能直接切换到深色主题和想要的颜色的主体

### ISSUE THREAD

**Issue by ahbksdmz** [Higurashi-kagome/wereader#106]
**请描述目前使用微信读书笔记助手遇到什么不便**

深色主体和其他主体共用一个按键，关闭深色主体后无法直接选择想要的主体，要按几下主题才能切换到。

**理想情况下，笔记助手应该怎么做**

深色主体和浅色主体（即其他颜色的主体）共用一个按键，当我关闭深色主体后可以直接切换到我想要的浅色主体。
浅色主体可以在一个按键中设置。
麻烦作者了，在此说声谢谢。
**额外信息**

可以参考一下起点的日间夜间设计和设置中的主体设置。

**Comment by Higurashi-kagome** [comment]
嗯，之后应该会给出一个颜色面板，可直接选择想要切换的颜色。

**Comment by ahbksdmz** [comment]
麻烦作者了
