### ISSUE TITLE
[Bug] 为什么这几天使用没有任何反应了

### ISSUE THREAD

**Issue by chujiu-vip** [Higurashi-kagome/wereader#107]
为什么这几天使用没有任何反应了

复制热评等等功能，全部失效

**Comment by Higurashi-kagome** [comment]
最近更新到了 Manifest V3，可以升级浏览器到最新试试。

**Comment by chujiu-vip** [comment]
已经是最新版的浏览器，插件也重新卸载安装了，还是不行，是我个人原因吗mac os ，mac book m1电脑
Chrome 徽标
Google Chrome
Chrome 已是最新版本
版本 116.0.5845.179（正式版本） (arm64)

**Comment by Higurashi-kagome** [comment]
我在 Windows 上好像没问题，可以参考 #70 看看有没有报错之类的。

**Comment by MaoFelix009** [comment]
Chrome 已是最新版本
版本 116.0.5845.187（正式版本） (arm64)

**Comment by MaoFelix009** [comment]
Error handling response: TypeError: Cannot read properties of undefined (reading 'url')
at chrome-extension://cmlenojlebcodibpdhmklglnbaghpdcg/worker.js:1:95423

**Comment by Higurashi-kagome** [comment]
一时还没发现问题（[issuecomment-1714917165](https://github.com/Higurashi-kagome/wereader/issues/107#issuecomment-1714917165) 中反馈的错误我这里暂时没出现），不太好排查，有时间可以尝试提供更多信息（在经过哪些步骤后出现问题之类，有哪些报错之类）。

最好是离线安装 [wereader.zip](https://github.com/Higurashi-kagome/wereader/files/12619920/wereader.zip)，然后获取标注，按 #70 检查是否有报错。

**Comment by chujiu-vip** [comment]
你可以远程我的电脑排查下吗，程序我不懂

**Comment by Higurashi-kagome** [comment]
嗯，可以和我通过 [higurashi-kagome@foxmail.com](mailto:higurashi-kagome@foxmail.com) 联系。
