### ISSUE TITLE
[Bug] ”获取我的想法-全部“操作时，想法的顺序错乱，内容重复

### ISSUE THREAD

**Issue by weiguozhu** [Higurashi-kagome/wereader#109]
**扩展是否为最新版本（与[扩展商店](https://chrome.google.com/webstore/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/cmlenojlebcodibpdhmklglnbaghpdcg?hl=zh-CN&authuser=0)中的版本相同）**

- [x] 是

**出现该问题的书本及章节（不方便公开的话可直接发[邮箱](mailto:higurashi-kagome@qq.com)告知）**

任何书籍。例如《当下的力量（白金版）》

**描述问题**

当点击”获取我的想法-全部“时，复制的想法并不是按照正确的章节组织的，而且会在每一个章节下重复。例如：A想法会跑到第一章下的某个地方，也会同时出现在第二章下的某个地方，有时候，章节的顺序也是错乱的。

**复现步骤**

1. 打开任何书籍。例如《当下的力量（白金版）》
2. 在不同章节发表想法
3. 点击”获取我的想法-全部“
4. 粘贴到别的编辑器
5. 同一想法出现多次，并且不在正确的章节下

**期待的正常行为**

想法在正确的章节下按顺序出现，且只出现一次。

**截图**

**额外信息**

**Comment by Higurashi-kagome** [comment]
v3.0.1 应该修复了，通过审核后可以试试。
