### ISSUE TITLE
微信疑似修改违规策略，开始封禁爬取内容的行为，今天登录发现被封5天

### ISSUE THREAD

**Issue by zionuke** [Higurashi-kagome/wereader#112]
![Screenshot_20231225_104815_com tencent weread_edit_184342190467182](https://github.com/Higurashi-kagome/wereader/assets/39029878/2886887e-3724-47e8-b724-2d1429cf4944)

**Comment by Higurashi-kagome** [comment]
只是使用了扩展就出现了这种情况吗，获取内容的频率怎么样？

**Comment by EasyIsAllYouNeed** [comment]
我永久被封了，，，，

**Comment by aptexd** [comment]
你们是不是高频操作啥了

**Comment by zionuke** [comment]
> 你好，问下只是使用了扩展就出现了这种情况吗，获取内容的频率怎么样？

抱歉很久没上 github，大概是读完一本书后开始导出划线笔记，获取内容频率较高；但之前没出现过封禁情况

**Comment by ZXiaolon** [comment]
wc我tm也突然被封了。之前安装了这个插件但是都没怎么用。找了半天问题。

**Comment by Achuan-2** [comment]
我也被封了

**Comment by Heart-of-engine** [comment]
> 我永久被封了，，，，

被封号之后还有解封的可能吗？我也是被封号了
