### ISSUE TITLE
[Feature] 模板 `metaData` 字段名单

### ISSUE THREAD

**Issue by Benature** [Higurashi-kagome/wereader#113]
1. 我想在「书本信息」导出模板中增加微信读书的网址，但不确定 `metaData` 是否含有这个信息且不知道字段名
2. 希望可以在设置区附近提供一个字段名单，尝试找了下没有找到。👉👈 

感谢开发这个插件！

**Comment by Higurashi-kagome** [comment]
确实加个清单才好，下次更新时会加入。

**Comment by Higurashi-kagome** [comment]
v5.1.0 补充了更多的字段信息，已发布到 Chrome。
