### ISSUE TITLE
[Bug] 使用插件差点要被封号了

### ISSUE THREAD

**Issue by AAAzzazaa** [Higurashi-kagome/wereader#116]
![WechatIMG18394](https://github.com/Higurashi-kagome/wereader/assets/156688319/0a288a70-071c-4183-9975-c66d9167dfc3)
只用了一次插件复制一些内容。。晚上就发现微信读书登陆不了了。。

**扩展是否为最新版本（与[扩展商店](https://chrome.google.com/webstore/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/cmlenojlebcodibpdhmklglnbaghpdcg?hl=zh-CN&authuser=0)中的版本相同）**

- [x] 是

**出现该问题的书本及章节（不方便公开的话可直接发[邮箱](mailto:higurashi-kagome@qq.com)告知）**

**描述问题**

**复现步骤**

**期待的正常行为**

**截图**

**额外信息**

**Comment by Higurashi-kagome** [comment]
好吧，之前有人反馈过，估计现在确实有限制。

**Comment by AAAzzazaa** [comment]
哎，好可惜

**Comment by Higurashi-kagome** [comment]
有时间我看看有没有其他方法支持。

**Comment by ZXiaolon** [comment]
我平时没打开这个插件。然后就复制书中文字+复制书中图片。突然就被封了。

**Comment by Achuan-2** [comment]
> 我平时没打开这个插件。然后就复制书中文字+复制书中图片。突然就被封了。

我也是被封之前没用导出功能，只是开启了划选自动复制功能，整理笔记，然后就被封了

**Comment by Higurashi-kagome** [comment]
嗯，下架了，可以和微信读书申诉看看。 @Achuan-2

**Comment by xbeta-zhang** [comment]
我开启的是「选中后自动马克笔划线」，准备继续冒险用下去😊
