### ISSUE TITLE
[Feature] 建议上架，但是提示可能的封号风险

### ISSUE THREAD

**Issue by aptexd** [Higurashi-kagome/wereader#117]
**请描述目前使用微信读书笔记助手遇到什么不便**

下架的有些匆忙啊
看了两个反应封号的，估计就是获取笔记比较频繁导致的吧
但我实在太需要画线后自动标注的功能了

**理想情况下，笔记助手应该怎么做**

或许可以对获取笔记时进行提醒，降低用户封号概率
一些不获取大量数据的操作，应该问题都不大吧
比如获取个书架，标注个笔记啥的问题都可以的

**额外信息**

得问清楚那些封号的人最近都做了哪些高频操作

**Comment by Higurashi-kagome** [comment]
v4.0.0 调整了数据获取方式，使用 debug 方式拦截网页数据（不再主动发起请求），并去掉了一些功能。已提交审核。

这个得看微信读书那边的限制是否严格了，比较严格的话原有版本确实可以做到导出一次就触发提醒，所以谨慎使用。
