### ISSUE TITLE
为什么chrome的复制热门标注功能没有了呢？edge浏览器还在

### ISSUE THREAD

**Issue by weqoocu** [Higurashi-kagome/wereader#118]
<img width="160" alt="image" src="https://github.com/Higurashi-kagome/wereader/assets/35360006/fd0e8eb0-fce0-4e6d-87e0-8040a793882b">

**Comment by Higurashi-kagome** [comment]
v4.0.0 将一些功能去掉了，因为有反馈存在封号的情况。虽然没测试是不是获取热门标注就会封号，但决定还是先去掉。后面可能会放开入口并给出必要的提示。

**Comment by weqoocu** [comment]
> v4.0.0 将一些功能去掉了，因为有反馈存在封号的情况。虽然没测试是不是获取热门标注就会封号，但决定还是先去掉。后面可能会放开入口并给出必要的提示。

我一直在使用，没有被封号，哈哈，期待恢复，一天使用过多可以提示有封号的风险

**Comment by weqoocu** [comment]
期待恢复啊

**Comment by Higurashi-kagome** [comment]
v5.0.0 已发布，恢复了热门标注获取功能。
