### ISSUE TITLE
[Bug] 选中后动作似乎失效了

### ISSUE THREAD

**Issue by 76563** [Higurashi-kagome/wereader#119]
**扩展是否为最新版本（与[扩展商店](https://chrome.google.com/webstore/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/cmlenojlebcodibpdhmklglnbaghpdcg?hl=zh-CN&authuser=0)中的版本相同）**

- [x] 是

**出现该问题的书本及章节（不方便公开的话可直接发[邮箱](mailto:higurashi-kagome@qq.com)告知）**

**描述问题**

前几天使用还是正常的，今天选中后动作马克笔/波浪线等等都失效了，我删除了插件又在edge商店重新下载了最新版本，还是没有解决
**复现步骤**

**期待的正常行为**

**截图**

![image](https://github.com/Higurashi-kagome/wereader/assets/106232184/26e2773f-abf5-421b-8498-93936d0365aa)

**额外信息**

**Comment by Higurashi-kagome** [comment]
是的，在最近的一次更新中把这个功能去掉了，因为有反馈称自动标注可能导致封号，虽然我没有认真确认，但还是决定先把这个功能去掉。之后如果测试正常，会再加回来。

**Comment by 76563** [comment]
> 是的，在最近的一次更新中把这个功能去掉了，因为有反馈称自动标注可能导致封号，虽然我没有认真确认，但还是决定先把这个功能去掉。之后如果测试正常，会再加回来。

原来如此，希望仍然能将这个功能加回来，或者说明风险后让用户自行选择，我3-4月都在高强度使用选中后划线，没有出现过封号。如果是3.28前后的封号，那可能是微信读书自身bug导致的（小红书上有相关讨论）
btw：感谢作者一直以来的维护，方便了我很多。新的一年祝你生活愉快~

**Comment by Higurashi-kagome** [comment]
v4.0.2 已加回该功能。不客气。
