### ISSUE TITLE
建议：可否为“选中后动作”增加一项“马克笔+复制”

### ISSUE THREAD

**Issue by xxhk-org** [Higurashi-kagome/wereader#120]
**请描述目前使用微信读书笔记助手遇到什么不便**

在对某一部分内容记笔记时，通常是需要先选中并马克或划线，然后再复制出来内容，目前都需要多步才能完成，如果可以的话，希望能改进一下。谢谢

**理想情况下，笔记助手应该怎么做**

马克+复制
划线+复制
……

**额外信息**

**Comment by Higurashi-kagome** [comment]
感觉可以，计划在下一个版本支持。

**Comment by Higurashi-kagome** [comment]
v5.1.0 已提交到 Chrome。
