### ISSUE TITLE
[Feature] 恢复书架功能

### ISSUE THREAD

**Issue by 2401hexu** [Higurashi-kagome/wereader#122]
**请描述目前使用微信读书笔记助手遇到什么不便**
以前可以管理书架的功能，之前找书很方便，现在怎么没有了？

**理想情况下，笔记助手应该怎么做**
可以再加入这个功能吗

**额外信息**

**Comment by Higurashi-kagome** [comment]
因为有反馈使用扩展可能会封号（#121），所以当时取消了几乎所有会主动发请求的功能。

计划在下一次更新时放开这个功能。

**Comment by Higurashi-kagome** [comment]
v5.1.0 已恢复书架功能。
