### ISSUE TITLE
[Bug] 取消导出标注包含所有章节，导出依然包含标注所属章节的子标题

### ISSUE THREAD

**Issue by Achuan-2** [Higurashi-kagome/wereader#123]
![Clip_2024-05-13_09-50-19](https://github.com/Higurashi-kagome/wereader/assets/60436214/c209e353-71a4-4ae5-9fd3-f04312fe3085)

取消导出标注包含所有章节，导出依然包含标注所属章节的子标题
![Clip_2024-05-13_09-53-56](https://github.com/Higurashi-kagome/wereader/assets/60436214/6ef114af-8449-4a7a-9238-b5fda3ca8b66)

**Comment by Higurashi-kagome** [comment]
我这里测试暂时是正常的，可以先勾选，再取消勾选试试。@Achuan-2

**Comment by Higurashi-kagome** [comment]
是的，这里的情况比较特殊，扩展只能够确认标注在该大标题下，而无法确认标注属于哪个子标题，所以会将所有子标题追加到大标题下，给用户自行编辑。@Achuan-2

**Comment by Achuan-2** [comment]
这个能加一个选项吗，只导出大标题，我自己是不需要子标题的，还得手动删

**Comment by Higurashi-kagome** [comment]
新版本 v5.1.0 已发布到 Chrome，支持该配置项：

<details>
<summary>Details</summary>

![image](https://github.com/Higurashi-kagome/wereader/assets/51501079/888ca953-248f-4202-92eb-6dd07eddf9cd)

</details>

扩展更新后可以试试。

**Comment by Achuan-2** [comment]
感谢大佬
