### ISSUE TITLE
“选中后动作”不起作用

### ISSUE THREAD

**Issue by DearOurselves** [Higurashi-kagome/wereader#125]
**扩展是否为最新版本（与[扩展商店](https://chrome.google.com/webstore/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/cmlenojlebcodibpdhmklglnbaghpdcg?hl=zh-CN&authuser=0)中的版本相同）**

- [Y ] 是

**出现该问题的书本及章节（不方便公开的话可直接发[邮箱](mailto:higurashi-kagome@qq.com)告知）**

与书本无关，所有的书本都有问题。

**描述问题**

用鼠标选择某一段文字，会弹出有“复制”“马克笔”“波浪线”等选项的对话框，而不是直接执行“选中后操作”

**复现步骤**

**期待的正常行为**

**截图**

**额外信息**

**Comment by Higurashi-kagome** [comment]
有注意到不再生效，将会在下次更新时修复。

**Comment by Higurashi-kagome** [comment]
v5.1.1 已发布到 Chrome 应用商店。

**Comment by DearOurselves** [comment]
非常感谢！
