### ISSUE TITLE
长按选择文本之后没有跳出功能选择栏

### ISSUE THREAD

**Issue by Stamp9** [Higurashi-kagome/wereader#19]
**请描述目前使用微信读书笔记助手遇到什么不便**

在安装插件前，选择文本后会跳出几个标注选项（波浪线/直线），复制，些想法之类的
安装插件之后，选择文本会直接跳出：已复制，没有跳出其他选项了；在选项里选择“选中后标注”之后，选文本会自动标注，但是也没有复制之类的选项

请问这是故意设计吗？还是bug

希望可以将自动标注作为选项，但是不要默认就复制或者标注，不然没法选波浪线等其他选项了

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。目前为止我没有遇到出现跳出“已复制”的情况，请问出现这种情况时你是选中了“选中后标注”中的哪个选项？将“选中后标注”设置为“无”是否还存在这种情况？另外，如果希望更改自动标注，可在扩展自动标注选中内容后，点击标注，然后在弹出的标注面板上选择其他标注类型。 @Stamp9

**Comment by Higurashi-kagome** [comment]
目前估计这是因为扩展没有初始化默认选项。如果你现在难以重现自动出现“已复制”的情景，那么基本上可以确定是这个原因。我将会在不久后发布新版本。感谢你的反馈。

**Comment by Stamp9** [comment]
> 感谢你的使用和反馈。目前为止我没有遇到出现跳出“已复制”的情况，请问出现这种情况时你是选中了“选中后标注”中的哪个选项？将“选中后标注”设置为“无”是否还存在这种情况？另外，如果希望更改标注类型，可在扩展自动标注选中内容后，点击标注，然后在弹出的标注面板上选择其他标注类型。 @Stamp9

您好，出现“已复制”情况是直接选中文本就出现的，没有点击选项，因为选项栏都没有跳出来；设置成“无”就是前文说的已复制状态。

**Comment by Higurashi-kagome** [comment]
好的，估计现在你在扩展设置页中选中除“无”之外的任意一个选项之后就不会再出现自动复制的情况了，你可以试试。 @Stamp9

**Comment by Stamp9** [comment]
> 好的，估计现在你在扩展设置页中选中除“无”之外的任意一个选项之后就不会再出现自动复制的情况了，你可以试试。 @Stamp9

试过了，已解决。谢谢！

**Comment by Higurashi-kagome** [comment]
新版本（v2.12.2）已更新至 Chrome 网上应用店，请注意更新。
