### ISSUE TITLE
导入书籍，无法导出我的想法。

### ISSUE THREAD

**Issue by ittenblunt** [Higurashi-kagome/wereader#21]
**设备信息**
- 操作系统: [Mac] 
- 浏览器版本: [Edge] 
- 扩展版本: [2.13] 

**描述问题**

看的导入书籍，划线，写想法，导出我的想法，没反应。

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈 @ittenblunt 。我在 Windows 上作了测试，但没能重现该情况。

首先，麻烦刷新读书页，然后，按照下面的演示勾选“收集错误”后重试：

<details>
<summary>Details1</summary>

![works](https://user-images.githubusercontent.com/51501079/105665057-1b2dc800-5f11-11eb-8757-f615c2540472.gif)

</details>

如果仍然没能像演示那样成功导出想法，按下面的演示查看插件的“背景页”控制台，如果控制台中有错误（红色或橙色的文字），麻烦提供给我：

<details>
<summary>Details2</summary>

![check](https://user-images.githubusercontent.com/51501079/105665064-1e28b880-5f11-11eb-8959-96f8cd311032.gif)

</details>

Regards.

**Comment by Higurashi-kagome** [comment]
刷新后应该不再存在这个问题了，不过对导入书籍的支持不太完善，还需要加强。
