### ISSUE TITLE
关于 Chrome 商店插件版本的问题

### ISSUE THREAD

**Issue by CareLaden** [Higurashi-kagome/wereader#22]
我又来来了，不知道你还记不记得我。

我最近整理笔记又用上你当初推荐给我的这个插件。然后我注意到 Github 上最新的是 2.15 版本，还是去年的。而 Chrome 商店的是 
2.13.0 版本，更新日期却是 2021 年 1 月 21 日。请问是因为开发者你个人习惯的问题是吗？

**Comment by Higurashi-kagome** [comment]
抱歉，不太记得了...

的确很久没有发布新的 [Releases](https://github.com/Higurashi-kagome/wereader/releases) 了，主要是因为扩展通常不需要在 Release 页面下载，而且我在开发的过程中没有注意维护版本更新信息（Commit 比较随意，Release 也只是用于记录版本），所以想阅读源码的开发者可能并不能从 Release 中获取易懂的信息😪。

我想我还是得注意维护一下才好😀。 @CareLaden

**Comment by CareLaden** [comment]
https://github.com/shengqiangzhang/examples-of-web-crawlers/issues/95 当初的讨论

原来如此，疑惑解决了，多谢解答。

**Comment by Higurashi-kagome** [comment]
不用谢，记起来了😁。
