### ISSUE TITLE
部分书籍导出的标题样式存在异常 [BUG]

### ISSUE THREAD

**Issue by CareLaden** [Higurashi-kagome/wereader#23]
经测试，发现微信读书的目录等级一些问题，例如这一本书导出目录的时候是按照 H1，但导出标注的时候，标题却成为了 H5 的样式。不知道是因为微信读书的原因还是插件本身的问题。

这本书 https://weread.qq.com/web/reader/6f4320407219b8bf6f4f97c 结果如下，存在问题
![image](https://user-images.githubusercontent.com/18063251/106373908-23767f00-63b9-11eb-941a-7a6e72fc3b4f.png)

第二本书是 https://weread.qq.com/web/reader/ea532d2071938fb5ea51430 结果如下，没存在问题
![image](https://user-images.githubusercontent.com/18063251/106373963-aef01000-63b9-11eb-8f70-5c625776304e.png)

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。这本书的确比较特殊，造成这种情况的原因是扩展在生成标注时通过向服务器发送请求来获取标题信息，而这本书返回的标题信息中并不包含标题级别（而一般书籍都有），所以扩展错误地生成了标题级别。
一个临时的解决方案是：对于这种标题不存在级别信息的书籍，将其标题视为一级。一个问题是，这样可能会导致无法识别多级标题（所有标题都被视为一级标题）。不过因为暂时还没遇到即存在多级标题又不包含标题信息的书籍，所以暂时采用这种处理方式。 @CareLaden

**Comment by CareLaden** [comment]
明白了，多谢解答。那我暂时手动处理，这类特殊情况的书籍目前也就发现这一本。

**Comment by Higurashi-kagome** [comment]
不用谢。最新版（v2.13.1）已更新至 Chrome 网上应用店，基本上解决了这个问题。

**Comment by 501830865** [comment]
可以告诉我这个导出微信读书的代码怎么用吗，我是一个货真价实的小白，什么都不懂，希望有人可以给我解答，我太需要了，可以吧需要的工具和步骤告诉我们。

**Comment by Higurashi-kagome** [comment]
如果你仅仅是需要使用工具来导出书本内容而不需要看代码，那么在[微信读书笔记助手 - Chrome 网上应用店](https://chrome.google.com/webstore/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/cmlenojlebcodibpdhmklglnbaghpdcg?hl=zh-CN)或[微信读书笔记助手 - Microsoft Edge Addons](https://microsoftedge.microsoft.com/addons/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/iblnlnnpkbhnempmcbioeholmemingmo)或[微信读书笔记助手 – Firefox 扩展（zh-CN）](https://addons.mozilla.org/zh-CN/firefox/addon/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/)中给浏览器安装插件即可。 @501830865
