### ISSUE TITLE
部分书籍的标注无法正常获取 [BUG]

### ISSUE THREAD

**Issue by CareLaden** [Higurashi-kagome/wereader#24]
获取本章是获取不到：
![image](https://user-images.githubusercontent.com/18063251/106377446-00a79300-63d8-11eb-9917-473c788b42ce.png)
获取全部可以抓取到：
![image](https://user-images.githubusercontent.com/18063251/106377453-0b622800-63d8-11eb-814a-dd7ebb0a306c.png)
获取全部抓取到得内容：
![image](https://user-images.githubusercontent.com/18063251/106377434-eff71d00-63d7-11eb-81d4-eed183410d34.png)

依旧是这本书：
https://weread.qq.com/web/reader/6f4320407219b8bf6f4f97c

**Comment by Higurashi-kagome** [comment]
是的，的确有这个问题。出现这种情况的原因是扩展从读书页的 DOM 上获取当前章节的标题。通常情况下，这样获取到的标题会存在于服务端的标题数据中，而这本书的服务端标题数据比网页中的标题要短（网页端多出了章节信息），比如，扩展从网页端获取到的当前章节标题为“第2章 刑与礼王子犯法与庶民同罪？都是骗人的”，而服务端的标题为“刑与礼王子犯法与庶民同罪？都是骗人的”（缺少章节），所以扩展无法从标注中找到当前章节，最终使得不能够正常导出本章标注。

现今的解决方案是，当服务端的标题包含于当前标题时（CurrentContent.indexOf(contents[key].title) > -1），视为两标题相同。 @CareLaden

**Comment by CareLaden** [comment]
好的，多谢解答
