### ISSUE TITLE
[Bug] 无法导出标题

### ISSUE THREAD

**Issue by CareLaden** [Higurashi-kagome/wereader#25]
https://weread.qq.com/web/reader/9b7322f05cd6c69b7ac3317kc7432af0210c74d97b01b1c

该书籍的标题无法抓取到，估计是上次那本书的修改代码后的影响？
![image](https://user-images.githubusercontent.com/18063251/107108017-ea825280-686f-11eb-8e38-984b37644b89.png)

**Comment by Higurashi-kagome** [comment]
感谢反馈。应该不是上一次更改的原因，这本书返回的标题数据中不只不存在标题级别（level），标题字符串（title）也为空。所以我尝试改变获取标题的方式，将其改为在从服务器请求数据的同时也从网页端获取标题，最后结合两者的信息来生成标题信息。

**Comment by Higurashi-kagome** [comment]
新版本（v2.13.2）已更新至 Chrome 网上应用店。
