### ISSUE TITLE
[Bug] 已勾选的情况下，导出想法不会带标注

### ISSUE THREAD

**Issue by CareLaden** [Higurashi-kagome/wereader#26]
![image](https://user-images.githubusercontent.com/18063251/108723812-a07fb900-755f-11eb-8e9c-506dfe255401.png)

最近导出想法的时候，发现标注不会一并导出，只有想法才能导出。功能是很早就启用的，之前没出现类似的问题。而且经过测试不单单是某本书的特殊问题。我把之前导出过的书籍重新导出一遍，也是一样的状况。

![image](https://user-images.githubusercontent.com/18063251/108723928-bee5b480-755f-11eb-8f7c-29101973637e.png)

**Comment by Higurashi-kagome** [comment]
感谢反馈。我暂时没有遇到该问题，请问插件是否为最新版（v2.14.3）？

**Comment by Higurashi-kagome** [comment]
新版本（v2.15.0）已在审核中，问题应该已解决，请注意更新。
