### ISSUE TITLE
[Bug] 导出标注包含想法失效

### ISSUE THREAD

**Issue by yukaze18** [Higurashi-kagome/wereader#27]
**设备信息**
- 操作系统: [win10] 
- 浏览器版本: [chrome88] 
- 扩展版本: [2.14.3] 

**描述问题**
在选项-其他中设置了导出标注包含想法，但是没有生效，导出的标注仍只有标注

**Comment by Higurashi-kagome** [comment]
感谢反馈。我暂时还没有遇到该情况，请问关闭“导出标注包含想法”之后再重新开启是否还会有这种情况？

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/109588447-b551e300-7b43-11eb-8ddd-893eceec6a78.png)

</details>

**Comment by yukaze18** [comment]
试了一下，还是出现这种情况

**Comment by Higurashi-kagome** [comment]
能否麻烦提供书本链接？或许是书本比较特殊。

**Comment by yukaze18** [comment]
https://weread.qq.com/web/reader/5fa32590716a2a315fa062a

这是链接

**Comment by Higurashi-kagome** [comment]
这的确是扩展的问题。新版本（v2.15.0）已在审核中，问题应该已解决，请注意更新。

**Comment by yukaze18** [comment]
好的，更新之后我会在测试反馈

**Comment by yukaze18** [comment]
问题已经解决，辛苦作者了
