### ISSUE TITLE
书架分类

### ISSUE THREAD

**Issue by lifesign** [Higurashi-kagome/wereader#28]
**请描述目前使用微信读书笔记助手遇到什么不便**
你好，看描述中支持书架分类，但是在书架页面貌似并没有看到，配置中也没有看到有相关选项，这个功能是还没有支持还是打开的姿势有问题呢？

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。目录只会在进入[书架页面](https://weread.qq.com/web/shelf)才会生成：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/110233950-8c29bc00-7f62-11eb-8eb2-b474146a5f40.png)

![image](https://user-images.githubusercontent.com/51501079/110234057-6e108b80-7f63-11eb-9a0c-6fa7da4822c8.png)

</details>

不过这时候此功能的确出了一点问题，所以即使进入书架页面也不能够正常显示。目前问题已修复，不久后将更新至 Chrome 扩展商店，请注意更新。

**Comment by Higurashi-kagome** [comment]
另外目前扩展需要进入书架页面才会生成书架，不太方便，未来可能将其添加至 popup。

**Comment by lifesign** [comment]
好的收到，我是刚下载的 Chrome 扩展商店版本，所以没有显示，坐等商店更新~ 😸

**Comment by lifesign** [comment]
你好，我看我 chrome 版本已经是 2.15.6，貌似进入书架页面 木有看到那个弹框
查看 console 有个报错

![image](https://user-images.githubusercontent.com/2189610/110406448-34539800-80bd-11eb-88c7-1f71b42b23c6.png)
![image](https://user-images.githubusercontent.com/2189610/110406464-3cabd300-80bd-11eb-9e51-ba1c17b5745d.png)

**Comment by Higurashi-kagome** [comment]
感谢反馈。我这边还没遇到该问题，所以可能是因为遇到了比较特殊的书籍。请问你是否能够使用下面的扩展压缩包来进行测试并将错误信息反馈给我？我在该扩展中添加了 `try-catch`：

```Javascript
try {
	splitedCover = categoryObjList[j].cover.split("/")
} catch (error) {
	console.error(error);
	console.warn(categoryObjList[j]);
	continue;
}
```

所以测试时应该能够从控制台获取到更多的信息。

[wereader-chrome.zip](https://github.com/Higurashi-kagome/wereader/files/6105380/wereader-chrome.zip)

测试过程中请先关闭从 Chrome 商店安装的笔记助手。如果不知道该如何解压测试请直接联系我。

**Comment by lifesign** [comment]
作者你好，根据你这个代码，看了下是个 undefined，我在打印了下 shelf 数据，应该是公众号类型中有个东西为 undefined 了
![image](https://user-images.githubusercontent.com/2189610/110411313-4df8dd80-80c5-11eb-8aed-878c1fe065fa.png)

**Comment by Higurashi-kagome** [comment]
好的，问题已重现，目前来看的确是这里的原因。我可能会在下一个版本中（今天或者明天发布）实现将书架显示在 popup 中并处理此处的错误，只是现在来看即使是新版本也可能暂时不能支持显示公众号及文章，因为书架页面没有相关信息。

**Comment by lifesign** [comment]
好的 可以的~ 另外微信读书自动组队这类的功能会考虑么

**Comment by Higurashi-kagome** [comment]
嗯，可能会。有开发者做出了[组队网站](https://weread.qnmlgb.tech/)（事实上还存在相应的浏览器扩展），如果未来尝试实现组队，则很可能会以该网站为基础来实现。

**Comment by Higurashi-kagome** [comment]
最新版（v2.16.0）已发布，请注意更新。
