### ISSUE TITLE
[Bug] 【导出热门标注+目录】功能导出的目录不完整

### ISSUE THREAD

**Issue by Tony-zf1** [Higurashi-kagome/wereader#29]
**设备信息**
- 操作系统: win10
- 浏览器版本: chrome88
- 扩展版本: 2.15.5

**描述问题**

您好，我是在chrome商店请您添加【导出热门标注+目录】功能的用户，在您更新后，发现存在一个小bug，如截图所示，导出后章标题下紧挨着的节标题（红框内）会缺失，而单独导出目录则不会出现这个问题。

测试书籍为罗翔的[刑法学讲义](https://weread.qq.com/web/reader/48032df071f3ab37480b27a)。

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/79450935/110283273-c0f94a00-801a-11eb-8604-0e790849abf6.png)

</details>

期待您的修复，谢谢！

**Comment by Higurashi-kagome** [comment]
感谢你详细的反馈。没能正常导出的标题比较特殊，完善后的新版本（v2.15.6）已在审核中，请注意更新。

扩展处理这类标题时仍然存在潜在的问题，未来可能会进一步完善。

**Comment by Tony-zf1** [comment]
> 感谢你详细地反馈。没能正常导出的标题比较特殊，完善后的新版本（v2.15.6）已在审核中，请注意更新。
> 
> 扩展处理这类标题时仍然存在潜在的问题，未来可能会进一步完善。

已经更新，谢谢！
