### ISSUE TITLE
[Bug] 书架分类不显示，控制台报错

### ISSUE THREAD

**Issue by superleeyom** [Higurashi-kagome/wereader#30]
**设备信息**

2.17.3
**描述问题**

书架功能失效

**复现步骤**

我怀疑是由于微信支持上传pdf造成的？

**截图**
![image](https://user-images.githubusercontent.com/22115219/112430319-edca9280-8d78-11eb-9b95-70d2e024521b.png)

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。的确是导入 PDF 所引发的问题，已尝试在最新版（v2.17.4）中修复，不久后将发布至 Chrome 扩展商店，请注意更新。

**Comment by superleeyom** [comment]
@Higurashi-kagome cool，多谢
