### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by marvinwu** [Higurashi-kagome/wereader#31]
**设备信息**
- 扩展版本: [] 
2.17.5

**描述问题**

获取标注功能不能用

**复现步骤**

**额外信息**

原本功能正常, 这几天开始不能用

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。目前最新版（v2.17.6）已在审核中，应该不存在该问题，麻烦更新并测试，如有问题请联系我。
