### ISSUE TITLE
[Feature] 可以自定义导出 markdown 格式吗？

### ISSUE THREAD

**Issue by qwgao1994** [Higurashi-kagome/wereader#32]
**请描述目前使用微信读书笔记助手遇到什么不便**

现在的 markdown 格式不是很符合我的阅读重点，所以想自定义导出。
因为我想把微信读书中划线的内容都导出然后打印，便于以后回看。所以可能更希望划线内容更重一些，自己的评论弱一些。
章节标题也希望可以显示的没有那么重要。

**理想情况下，笔记助手应该怎么做**

所以我希望的自定义格式为：

`这是章节标题`
==这是划线内容==
>这是我的评论

参考：

·`魔性附身`
人类如果不扎根于X先生所说的正常的生活，迟早有一天会在精神上走进越来越窄的死胡同，生理上的思考能力和判断能力也会日渐衰弱。如果陷入这种状态，人就只能看到眼前的利害得失，彻底沦为欲望的奴隶。

>越爱科技，越讨厌社交

**额外信息**

我在即刻上发了个帖子寻求帮助，原文是这样的：
>有没有什么工具可以把微信阅读的划线和笔记用API导出，再填进自定义好格式的PDF里面呢？
今天看了WebMerge 只能按一条条划线直接转一个PDF文档，也就是说一条划线一页纸。
我想把所有的划线笔记自动排版🤣这样就可以直接打印成册了。

这两天翻到以前上学时候写的读书笔记，有的是摘抄的一句话，有的是一些思考。时隔几年年翻开，一下子看进去了好久...

现在很多看书都是在微信阅读上看，就想把这些记录印成小册子，隔几个月还能看看当时mark的内容。

==于是有热心的即友推荐了您的插件作品，体验后唯一还不太合适我古怪的需求的就是这个啦。==

附上我自己画的阅读排版：

<details>
<summary>Details</summary>

<img width="607" alt="截屏2021-04-24 下午10 37 30" src="https://user-images.githubusercontent.com/65410402/115962383-ad179200-a54d-11eb-937f-5cc97ab94b11.png">

</details>

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。

将想法放在引用块中可通过为想法添加前缀 `> `（注意右侧有一个空格）同时将想法后缀设置为空来实现：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/115963075-c3731d00-a550-11eb-9dab-ad1882b850ed.png)

</details>

因为目前扩展只支持给标题添加前缀，所以并不能直接将标题放在行内代码之类的元素中，如果希望标题不那么明显，可尝试将所有标题的前缀都设置为 Markdown 中的六级标题（当然设置为四级或五级也行）：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/115963331-76dc1180-a551-11eb-9819-9e0a8ad5841f.png)

</details>

如果这样不能够满足需求，那么可尝试用正则表达式手动对标题进行替换，比如，假如导出了下面一段包含标题的文本：

```markdown
###### 这是章节标题

==这是划线内容==

> 这是我的评论

###### 魔性附身

人类如果不扎根于X先生所说的正常的生活，迟早有一天会在精神上走进越来越窄的死胡同，生理上的思考能力和判断能力也会日渐衰弱。如果陷入这种状态，人就只能看到眼前的利害得失，彻底沦为欲望的奴隶。

> 越爱科技，越讨厌社交
```

那么可以通过使用 `###### (.*$)` 来匹配文本，使用 <code>\`$1\`</code> 来对原内容进行替换，使其显示为 Markdown 中的行内代码：

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/115963660-ebfc1680-a552-11eb-8b93-cdfe23b450fe.gif)

</details>

不过考虑到这需要手动操作，比较麻烦，所以我可能会在下一个版本中支持为标题添加后缀。

**Comment by Higurashi-kagome** [comment]
已支持为标题添加后缀，不久后将更新至 Chrome 网上应用店。
