### ISSUE TITLE
希望能添加管理书架的功能

### ISSUE THREAD

**Issue by longshensanjie** [Higurashi-kagome/wereader#33]
**请描述目前使用微信读书笔记助手遇到什么不便**
我是主力 PC 网页端微信读书重度用户, 希望能添加管理书架的内容, 在网页端直接上传了自己下载的电子书之后如果想要更改, 还需要到移动端去管理, 觉得非常的麻烦, 另外有个比较小众的需求, 就是显示书架当中的公众号内容, 一直以来微信公众号内容都是比较封闭的, 除非在自家app或者微信上才能查看, 通过这个方案的话提供了一个在 PC 上查看微信公众号的途径, 个人感觉还是一个蛮亮眼吸引人的小功能, 当然这只是我的个人主观感受, 这个需求如果实现很麻烦的话也可以否掉

**理想情况下，笔记助手应该怎么做**
我期待的话可以直接在 **查看我的书架** 页面直接进行整理, 在 **余额** 下一列增加一些操作按钮, 在当前页面进行各自移动端的管理操作, 至于公众号显示操作的话就正常和书籍的逻辑一样就好

**额外信息**
虽然需求提了但是实现方案好像说的比较模糊, 具体我觉得可以以 **微信读书助手**  这款软件对于上述两个功能的实现作为参考, 另外个人非常喜欢这款插件的简洁, 使用了一段时间了还有个小小的感受, 就单纯觉得这个统计页面属实有点意义不大的感觉, 虽然我暂时也没有特别好的方案提供, 最后感谢作者的辛勤付出 ❤

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。都是很好的建议。

我将会尝试支持显示公众号内容，不过难说是否能够实现，其他的功能可能会在明天更新支持。

**Comment by longshensanjie** [comment]
> 感谢你的使用和反馈。都是很好的建议。
> 
> 我将会尝试支持显示公众号内容，不过难说是否能够实现，其他的功能可能会在明天更新支持。

嗯嗯, 感谢你的回复, 关于公众号内容显示，个人觉得没有很好的方式的话, 也可考虑就给出个类似书籍封面在书架列表, 点击的话弹出一个最近的更新列表页面, 点击某一篇直接跳转到微信公众号的网页链接就好了, 就单纯做个显示跳转中转的功能就已经很好啦, 当然具体实现难度和可能性还是得看你评估, 如果实现很麻烦或不可能的话也可砍掉这个需求, 总之感谢你的付出❤

**Comment by Higurashi-kagome** [comment]
好的，我有查到 **微信读书助手** 支持公众号查看，因此这个功能应该会实现。

**Comment by longshensanjie** [comment]
嗯嗯, 好的, 期待ing, 慢慢来

**Comment by Higurashi-kagome** [comment]
v2.18.0 版本已在审核中，不久后将发布至 Chrome 网上应用店，请注意更新。

如遇到可能存在的问题，或者有其他的建议，请直接反馈给我。
