### ISSUE TITLE
管理书架页面出现落位现象

### ISSUE THREAD

**Issue by longshensanjie** [Higurashi-kagome/wereader#34]
**设备信息**
- 扩展版本: v2.18.1

**描述问题**
**管理书架** 页面当书籍上方出现复选框时候, 添加书籍封面和其他的书籍封面落位, 显示错位

**复现步骤**
打开管理书架页面即可复现 bug

**期待的正常行为**
添加书籍封面和其他的书籍封面保持对齐

**截图**
![image](https://user-images.githubusercontent.com/16282697/116661152-98605180-a9c6-11eb-9362-7d456ef21226.png)

**额外信息**
**建议**: 在公众号文章列表页面提供一个返回 **微信读书** 主页面的按钮 (能返回主页面的方式都可)

往常书籍的话, 点进去的话可以通过点击以下的按钮的方式返回 

![image](https://user-images.githubusercontent.com/16282697/116661600-4966ec00-a9c7-11eb-972d-7288772b8729.png)

我的应用场景是直接通过插件的 **书架** 列表直接进入公众号文章列表界面, 但是现在公众号页面只呈现文章列表, 想返回必须重新输入微信读书的网址或者通过 **书架** 当中其他书本作为跳转, 稍微有点麻烦

**另一个不知道是不是bug**: 另外有时候我直接通过鼠标左键插件 **书架** 列表直接进入读书页面的时候(没有打开微信读书页面), 偶尔会显示获取数据失败的情况, 这个我中间出现了一次, 现在很难复现了

**Comment by Higurashi-kagome** [comment]
样式已完善，已添加跳转链接。新版本将会今天内发布。

的确偶尔会出现获取失败的情况，但还没有找到好的解决方案，所以暂时还不能修复这个问题。
