### ISSUE TITLE
微信读书公众号 功能增强建议

### ISSUE THREAD

**Issue by bighaidao** [Higurashi-kagome/wereader#36]
**请描述目前使用微信读书笔记助手遇到什么不便**

公众号文章这个功能很赞。很多时候想电脑阅读公众号非常麻烦，有了这个功能后很有帮助。
但是发现有个小痛点。公众号历史文章很多，每次加载更多仅显示一小部分，想查看很老文章，需要翻阅很久。 

**理想情况下，笔记助手应该怎么做**

希望能增强下，提高历史文章的 get 能力
1、无文章首页图模式，提高一屏显示文章量，
2、加载更多 功能能提高加载文章量。目前看加载更多有点少了。

**额外信息**

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。

建议很好，但为了简化问题，我只是实现了一个自动加载下一页的功能，该选项默认打开：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/117570038-29d46f80-b0fb-11eb-8c6b-fa484e3c0f02.png)

</details>

或许能够满足查看历史文章的需求。实现该功能的 v2.19.3 版本将在不久后发布，请注意更新。
