### ISSUE TITLE
微信公众号文章 页面列表增强建议

### ISSUE THREAD

**Issue by longshensanjie** [Higurashi-kagome/wereader#37]
请描述目前使用微信读书笔记助手遇到什么不便

hi, 老哥, 我又来了, 在体验了一段时间之后, 发现了一点小的体验上的问题, 上一个 issue已经提到了一点关于文章太多显示导致翻看很老文章，需要翻阅很久的问题, 这也是我想讨论的东西, 但是我还想说的更具体和深入一点并给出我的想法和建议

问题:

公众号页面为啥会觉得一页看不了很多,  我根据我的使用经历来分析主要是下面两个原因

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/16282697/117574374-5abe9f80-b10f-11eb-97f5-fbe8c60f2663.png)

</details>

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/16282697/117574461-c1dc5400-b10f-11eb-95ee-4541aa9cf186.png)

</details>

理想情况下，笔记助手应该怎么做

先说说我的预期效果

1. 我希望每一次的推送文章样式是**统一**的, 这样至少在观看体验上是舒服的 (统一不一定是全部一样, 我下面有截图可理解)

2. 我希望每次的推送是**以时间作为节点**的而不是以单篇文章作为节点的, 可能说的有点抽象我以移动端微信公众号推送举例

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/16282697/117574924-28627180-b112-11eb-82f6-475b9264e556.png)

</details>

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/16282697/117574969-5e075a80-b112-11eb-8f47-d0590bf7434e.png)

</details>

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/16282697/117575012-88591800-b112-11eb-8f2a-c144f842bd72.png)

</details>

样式基本上可以分为两种大情况, **一种是某一时间节点只推送了单篇文章,** **另一种是一次性推送了多篇** 

额外信息

我相信通过**页面布局统一**和**按照时间点来整合微信公众号列表** 应该能解决翻阅太久的问题, 也能大大提高页面的美观和便利程度, 就是不知道实现以上我说的效果依据现有的接口好不好进行实现, 当然这些都是我自己使用下来的体验和我觉得如何实现会比较好的个人建议, 跟之前一样, 具体能否实现还是得看你这边具体的技术实现难度, 总之还是非常感谢你的每一次认真聆听和更新❤

额外彩蛋

刚刚写 issue 写到一半的时候, 突发奇想, 如果上面的功能效果能实现的话, 也许还能实现如下图建议的彩蛋小功能

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/16282697/117575495-afb0e480-b114-11eb-87d7-ced1e3b8b480.png)

</details>

默认白天模式, 搭配微信读书夜间版可切换成夜间模式微信公众号页面样式. 嘿嘿

**Comment by Higurashi-kagome** [comment]
嗯，的确是可以完善的点，应该会加在下一个版本中。不过因为最近比较忙，所以可能不会那么快实现，需要等待一段时间。

**Comment by Higurashi-kagome** [comment]
修复文字较多时图片显示不佳的问题；

时间置于面板顶部；

摘要内容本身就不完整，而且没有打算直接在末尾加特殊符号，因为有的公众号摘要有被认真管理（本身是完整的），所以暂时不会修复（恐怕以后也不会修复了）；

已支持过长内容省略显示；

因为在图片中添加文字会影响图片的视觉效果，个人觉得不太美观，所以标题位置保持不变，没有将其置于图片内部。

新版本（v2.19.5）将在不久后发布。

**Comment by longshensanjie** [comment]
嗯嗯 试了下 发现时间置于面板顶部这个改动非常棒 (我当时第一想法也是这个, 不过觉得换个位置对你来说比较好改)

个人而言, 聚合页面去掉简介之后, 第一行标题和第二行这块之间的样式还是有点违和, 怪怪的, 但是我好像也没什么比较好的方案, 不过惊喜的是, 经过改良简介省略显示之后的聚合页面样式居然意外的觉得很好看, 很不错, 大概会成为我的默认样式, 哈哈

整体而言, 这些改动都很棒, 暂时将我对于公众号页面的脑子里的构想和需求都被很好的实现和满足了, 非常感谢你的更新❤
