### ISSUE TITLE
导出标注和我的想法能否多一个合并的功能.

### ISSUE THREAD

**Issue by dmjstudy** [Higurashi-kagome/wereader#39]
**请描述目前使用微信读书笔记助手遇到什么不便**

分别导出标注与想法,还要找对应的章节去复制粘贴,工作量大,很不方便.

**理想情况下，笔记助手应该怎么做**

能否多一个合并导出标注与我的想法的功能 ?谢谢

**额外信息**

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。扩展支持在导出标注时导出想法，该功能需要在选项页中开启“导出标注包含想法”：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/117967307-761beb80-b357-11eb-9397-b4103f876bc5.png)

</details>
