### ISSUE TITLE
欢迎反馈~

### ISSUE THREAD

**Issue by Higurashi-kagome** [Higurashi-kagome/wereader#4]
在使用过程中遇到任何问题，都可以直接在这里提 Issue，或者通过邮箱联系我：higurashi-kagome@qq.com

不用担心我会不会回复，能够看见这条提示，说明任何反馈都会得到重视⭐️。

**Comment by ZQuanTong** [comment]
edge 浏览器，找不到bg的定义
https://github.com/liuhao326/wereader/blob/205f74642e1f3301e70a0ff2790203bfcc500f18/wereader-chrome/popup/popup.js#L83

**Comment by liuhao326** [comment]
感谢反馈，目前为止我没有遇到该情况，能否提供重现步骤？ @ZQuanTong

**Comment by tongyuzhao-9** [comment]
勾选导出标注包含想法后，只会复制想法对应的原文，不会导出想法本身。@Higurashi-kagome

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈，问题已修复，不久后将更新至 Chrome 扩展商店，请注意更新。 @tongyuzhao-9
