### ISSUE TITLE
关于微信公众号页面 上方按钮的摆放顺序建议

### ISSUE THREAD

**Issue by longshensanjie** [Higurashi-kagome/wereader#41]
**请描述目前使用微信读书笔记助手遇到什么不便**
当前微信公众号页面设有 **微信读书商城** 和 **返回书架查看**两个返回按钮, 使用一段时间下来发现一点小体验的问题, 就是习惯性的想去点左上方的按钮, 但是我的需求却是想直接返回书架, 虽然看起来很奇怪好像在吹毛求疵, 但是确实是很重要的体验

![image](https://user-images.githubusercontent.com/16282697/118058382-b1063980-b3c0-11eb-8a6b-e0806410f860.png)

那么什么是微信公众号页面这个页面最常用和期望的操作呢, 当然是返回书架页面, 一方面的理由是这个页面本来是由书架页面跳转过来的, 书架本来就是这个页面的上一级操作, 另一方面, 最主要的原因是微信书城初始页面未显示微信公众号书籍, 我想切换另一个公众号阅读的切换成本变高了

**理想情况下，笔记助手应该怎么做**
将左上放置最常用的功能, 右上换成较少使用的功能, **简单来说, 就是互换位置**

**额外信息**
作者应该从未见过如此吹毛求疵之人吧, 哈哈, 别打我

**Comment by Higurashi-kagome** [comment]
我考虑一下🤣，今天应该不会更新，需要等会儿。

**Comment by Higurashi-kagome** [comment]
对我来说一般会倾向于点击右侧的链接，可能不同的人有不同的倾向，所以更改位置不见得能够达到目的。现在的问题或许更主要是因为“去书架查看”对于读者来说太陌生了，所以我计划将其换成“返回书架”，这样表意更清晰：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/118077158-26383580-b3e6-11eb-8010-8e78524fd049.png)

</details>

**Comment by longshensanjie** [comment]
> 对我来说一般会倾向于点击右侧的链接，可能不同的人有不同的倾向，所以更改位置不见得能够达到目的。现在的问题或许更主要是因为“去书架查看”对于读者来说太陌生了，所以我计划将其换成“返回书架”，这样表意更清晰：
> 
> Details
> ![image](https://user-images.githubusercontent.com/51501079/118077158-26383580-b3e6-11eb-8010-8e78524fd049.png)

嗯嗯, 我觉得你说的有些道理, 换位置确实解决不了根本问题, 一方面确实是因为“去书架查看”对于读者来说太陌生了, 按照这个思路, 同样也是因为 "微信读书书城" 这几个字陌生放在这很奇怪, 从这个出发点去思考解决方案的话, 我觉得**图标**是很好的解释方案

![image](https://user-images.githubusercontent.com/16282697/118091191-21cb4700-b3fd-11eb-879c-a813f32464a0.png)
 
微信读书阅读界面的顶部样式, 我觉得有借鉴意义, 也有利于风格的一致

**ps:**
这里的图标或图标加文字鼠标划上去有高亮的效果, 也很漂亮和舒服( 你懂的

额外信息:
除此之外, 有一点强烈的感受是**插件的设置隐藏太隐蔽了**, 我估计用插件还有一大半的人都甚至不知道居然还有一些设置功能, 设置的功能分类感觉也有点杂乱, 虽然我也没有具体完善的方案给出, 但是有一点思路, 举个例子就是微信公众号相关的设置可以以视觉化的形式出现在微信页面当中呈现进而选择然后自动刷新看到效果, 其他的设置选择也类似, 想法批注这些设置功能都慢慢融入到阅读界面当中去, 我感觉一方面功能更显眼了也更易用了, 不过这只是一个不太成熟的想法, 具体设计融入到页面当中怎么契合和以哪种视觉化的方式去呈现比较好我觉得都是一个比较费时间考量的事情, 算是一个插件未来完善的一个小方向吧

**Comment by Higurashi-kagome** [comment]
嗯，后面会将选项页入口加到 popup 中，并且会进一步完善帮助说明。但这几天应该都不会更新，会需要等待一段时间。

**Comment by longshensanjie** [comment]
> 嗯，后面会将选项页入口加到 popup 中，并且会进一步完善帮助说明。但这几天应该都不会更新，会需要等待一段时间。

嗯嗯, 好的

**Comment by Higurashi-kagome** [comment]
抱歉没能及时回复。

我尝试添加了与阅读页相同的图标：

<details>
<summary>Details</summary>

![Clip_20210517_105126](https://user-images.githubusercontent.com/51501079/118504064-c7641a80-b75d-11eb-8155-c0e99efe42c5.png)

![Clip_20210517_105253](https://user-images.githubusercontent.com/51501079/118504078-cb903800-b75d-11eb-916c-8ad095e5add6.png)

</details>

然而总的来说效果似乎并不比原样式要更好：

<details>
<summary>Details</summary>

![Clip_20210517_104416](https://user-images.githubusercontent.com/51501079/118504222-e793d980-b75d-11eb-8be5-cfc980db6ea0.png)

</details>

虽然图标带来的指示更加形象，但因为文字本身并不复杂，使用者应该能够比较顺利地使用，所以为保持简洁我没有添加图标，不过（如你所见）为所有链接添加了 hover 样式：

<details>
<summary>Details</summary>

![Clip_20210517_221509](https://user-images.githubusercontent.com/51501079/118504602-3c375480-b75e-11eb-9cd2-f758af262ee2.png)

</details>

因为设置不常需要改变，将其置于常去的页面可能会显得多余，所以我没有将其分散到其他更加明显的地方，而仅仅是在 popup 中提供了一个设置页入口。另外现在的设置功能的确多而杂，不太方便入手，未来可能会通过完善设置页面中的帮助信息来进一步解释各选项的作用。
