### ISSUE TITLE
[Feature] 图片导出功能

### ISSUE THREAD

**Issue by iceyasha** [Higurashi-kagome/wereader#42]
**请描述目前使用微信读书笔记助手遇到什么不便**

微信读书导出的图片是官方链接，可能存在图片链接失效的问题

**理想情况下，笔记助手应该怎么做**

1. 笔记导出时，应该自动上传图片至图床/本地磁盘，可以在配置中指定图床
2. 图片格式应该支持配置，现在支持 Markdown 这种格式：
`![image](https://asset.logseq.com/static/img/logo.png) `
还希望支持 org-mode 图片格式：
`[[https://asset.logseq.com/static/img/logo.png][image]]`

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。

图片的问题可能由其他软件来解决要更合适，因为它们能提供更加完整的功能，比如，Typora 支持自动将网络保存到本地，这意味着只需使用扩展复制到包含图片的 Markdown 文本，然后在 Typora 中粘贴即可得到所有图片（并相应地更新 Markdown 图片链接）；另外，可借助 PicGo 来上传图片到网络（并自动复制上传后的图片链接）。

所以，扩展很可能不会支持将图片上传到图床或是下载到本地。

org-mode 的图片格式可能会支持，但应该会需要等待一段时间，如果急着解决这个问题，建议使用正则表达式模式`!\[([^\]]*)\]\(([^)]*)\)`及替换值`[[$2][$1]]`来替换原 Markdown 文本：

<details>
<summary>Details</summary>

![demo1](https://user-images.githubusercontent.com/51501079/119332404-1c061900-bcbb-11eb-80dc-1b1a3ee6e0d7.gif)

</details>

**Comment by iceyasha** [comment]
> 感谢你的使用和反馈。
> 
> 图片的问题可能由其他软件来解决要更合适，因为它们能提供更加完整的功能，比如，Typora 支持自动将网络保存到本地，这意味着只需使用扩展复制到包含图片的 Markdown 文本，然后在 Typora 中粘贴即可得到所有图片（并相应地更新 Markdown 图片链接）；另外，可借助 PicGo 来上传图片到网络（并自动复制上传后的图片链接）。
> 
> 所以，扩展很可能不会支持将图片上传到图床或是下载到本地。
> 
> org-mode 的图片格式可能会支持，但应该会需要等待一段时间，如果急着解决这个问题，建议使用正则表达式模式`!\[([^\]]*)\]\(([^)]*)\)`及替换值`[[$2][$1]]`来替换原 Markdown 文本：
> 
> Details

感谢你的解答
