### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by NetworkThought** [Higurashi-kagome/wereader#44]
**请描述目前使用微信读书笔记助手遇到什么不便**

不能同时导出标注和想法

**理想情况下，笔记助手应该怎么做**

增加一个选项, 可以同时导出标注和想法, 想法可以在下一行, 并且缩进.

**额外信息**

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。该功能是支持的，生效前需要在设置页中打开如下选项：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/126060058-5cb4d303-0f62-4cb6-9bf5-d3fd6d30b276.png)

</details>
