### ISSUE TITLE
[Bug] 导出标注后章节标题两次重复出现

### ISSUE THREAD

**Issue by jarodise** [Higurashi-kagome/wereader#45]
**设备信息**
- 扩展版本: []  2.19.23

**描述问题**
 导出标注，粘贴到笔记软件内，发现部分书籍（特别是英文书）所有的章节二级标题都会重复出现两次。

**复现步骤**

**期待的正常行为**

二级章节标题应该只出现一次，否则还要手动删除。

**截图**

![Xnip2021-08-30_12-37-18](https://user-images.githubusercontent.com/15899808/131327120-ab2fe8db-4df0-470b-9cc9-a97807c47ac2.jpg)

**额外信息**

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。如果可以的话，建议附上出现该情况的书本以方便测试。 @jarodise

**Comment by jarodise** [comment]
> 感谢你的使用和反馈。如果可以的话，建议附上出现该情况的书本以方便测试。 @jarodise

感谢回复，请通过下方链接下载测试epub文件。该链接有效期为从今日起一周。
https://we.tl/t-ytEZOkEd2T

**Comment by Higurashi-kagome** [comment]
问题已修复，v2.19.24 不久之后将更新至 Chrome 网上应用店，请注意更新。 @jarodise
