### ISSUE TITLE
[Feature] 一键复制所有当日阅读书籍的笔记

### ISSUE THREAD

**Issue by jarodise** [Higurashi-kagome/wereader#46]
很多时候一天之内要同时读好多本书，在不同的章节记录笔记。每天总结当日读书进度的时候，还需要到每本读过的书里面分别进行导出就显得有些繁琐。现在很多的PKM软件例如Roam Research, Obsidian，Logseq都是以Daily Journal为信息录入核心节点的，能否考虑添加这样一个功能: 一键复制当日阅读所有书籍读书笔记。抓取当日零点至操作时间点之间打开阅读并且标注过的读书笔记。这样会方便很多。

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈，我会考虑是否实现该功能。会要等待一段时间，一般最早要到本周末才能够实现。

**Comment by Higurashi-kagome** [comment]
该功能已没有计划实现。因为通常情况下，总结是以某书/某章节为单位的，以天为单位获取标注，更多地应该是为了回顾。做系统的总结的时候，仍然会要回到某本书的某一章上。
