### ISSUE TITLE
开的时间久一点就会很卡

### ISSUE THREAD

**Issue by HeiLon** [Higurashi-kagome/wereader#48]
Microsoft Edge版本 95.0.1020.44 (官方内部版本) (64 位)

wereader版本 2.19.25 

开的时间久一点就会很卡，复制什么的都要等很久

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。 @HeiLon 

简单检查之后没有发现问题，建议你提供完整的复现步骤（比如出现问题的书本等等），或者是提前进入扩展管理页面开启“收集错误”选项，然后开始使用扩展，在使用过程中出现问题时打开背景页检查背景页中是否有出现红色的错误打印：

<details>
<summary>进入扩展管理页面</summary>

![image](https://user-images.githubusercontent.com/51501079/141097680-88b01e4e-db02-4ca4-94a5-43e3b5537093.png)

</details>

<details>
<summary>提前开启“收集错误”选项</summary>

![image](https://user-images.githubusercontent.com/51501079/141097797-1a3d0d19-5a2d-4543-a102-0a978a2b8c2a.png)

</details>

<details>
<summary>在遇到问题（比如卡顿）时打开背景页</summary>

![image](https://user-images.githubusercontent.com/51501079/141097902-f01ada8f-9f99-4637-bcb6-659540622983.png)

</details>

<details>
<summary>进入“控制台”，检查控制台中是否打印有错误</summary>

![image](https://user-images.githubusercontent.com/51501079/141098061-b32d398b-c65e-49cc-987d-44f388a08284.png)

</details>

如果打印有错误，请将错误信息复制并反馈给我。
