### ISSUE TITLE
[Bug] 四级标题和其对应的笔记分离

### ISSUE THREAD

**Issue by agentsl** [Higurashi-kagome/wereader#49]
**设备信息**
- 扩展版本: [2.19.25] 

**描述问题**
具体表现是：
```
### 三级标题1
#### 四级标题1
#### 四级标题2
#### 四级标题3

> 四级标题1下笔记1
> 四级标题1下笔记2
> 四级标题2下笔记1
> 四级标题3下笔记1
> 四级标题3下笔记2
> 四级标题3下笔记3
...

### 三级标题2
#### 四级标题1
#### 四级标题2
#### 四级标题3

> 四级标题1下笔记1
> 四级标题2下笔记1
> 四级标题2下笔记2
> 四级标题3下笔记1
> 四级标题3下笔记2
...

### 四级标题3
...
```

**复现步骤**
点击获取标注，无论选择本章或全部，都存在这个问题。

**期待的正常行为**
每个四级标题下有其对应标题的笔记。

**额外信息**
谢谢！

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。如果可以的话，麻烦提供出现此问题的书本，以方便测试。 @agentsl

**Comment by Higurashi-kagome** [comment]
好的。虽然有了一点思路，但我还是决定在 12 月 22 日之后再尝试修复该问题，因为我有一门考试需要准备。望理解。 @agentsl

**Comment by agentsl** [comment]
不急的，有这么好用的插件就十分感谢啦。祝你考试顺利！

**Comment by Higurashi-kagome** [comment]
我找到了出现该问题的原因，但没有解决的思路，也就是说这个问题我没有能力修复。抱歉。

出现这个问题是因为这本书的四级标题在微信读书中与一般标题不同，它属于三级标题下的**锚点**。扩展只支持将这类标题追加到它的上级标题上，而不能够保证其在正确的标注前。

必须要说的是，可能以后我也不再会尝试修复该问题（但我不介意保持该 Issue 打开，因为或许会有其他人感兴趣），虽然它是一个明显的漏洞。我想，将时间花在其他需要完善的问题上会更好，希望其他方面的改进能够弥补该不足。

另外，考试算是相当顺利，谢谢你的祝福 @agentsl 。😄

**Comment by agentsl** [comment]
感谢！
我试了其他书，四级标题也是没问题的。这可以说是微信读书中某些书的格式不统一的问题，严格意义上不算扩展本身的bug。其实可以关闭啦。
🎄圣诞快乐～
