### ISSUE TITLE
[Feature] 被标记的图片无法右键保存

### ISSUE THREAD

**Issue by goodluck233** [Higurashi-kagome/wereader#50]
**请描述目前使用微信读书笔记助手遇到什么不便**

对于微信笔记中划了线的图片，无法保存

**理想情况下，笔记助手应该怎么做**

希望当选中图片时（哪怕是划了线的），能够ctrl+c复制图片

**额外信息**

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。已简单修复该问题，大概会在明天会发布新版本。没有支持 Ctrl + C 复制图片，但是当图片被标注的时候，可以先将光标悬浮在图片上方，然后按下 Ctrl 键将标注隐藏，之后就可以进行右键操作了。

**Comment by goodluck233** [comment]
你的插件真的很好用，也感谢你开发的插件。



---原始邮件---
发件人: "Hao ***@***.***&gt;
发送时间: 2021年12月22日(周三) 晚上9:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Higurashi-kagome/wereader] [Feature] 被标记的图片无法右键保存 (Issue #50)




 
感谢你的使用和反馈。已简单修复该问题，大概会在明天会发布新版本。没有支持 Ctrl + C 复制图片，但是当图片被标注的时候，可以先将光标悬浮在图片上方，然后按下 Ctrl 键将标注隐藏，之后就可以进行右键操作了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
