### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dragon-liu** [Higurashi-kagome/wereader#51]
**设备信息**
- 扩展版本: [v2.19.26] 

**描述问题**

获取标注时只能获取一级和二级标题，三级标题开始无法获取

**复现步骤**

1. 比如[这本书](https://weread.qq.com/web/reader/751326d0720befab7514782kc81322c012c81e728d9d180)第一章1.2节JavaScript实现
2. 我只对正文内容进行了标注，导出时可以获得如下格式
```
### 1.2 JavaScript实现
虽然JavaScript和ECMAScript基本上是同义词，但JavaScript远远不限于ECMA-262所定义的那样。没错，完整的JavaScript实现包含以下几个部分（见图1-1）：

这里有一个三级标题 1.2.1 ECMAScript 并未导出

ECMAScript，即ECMA-262定义的语言，并不局限于Web浏览器。

后面还有一个四级标题 1．ECMAScript版本 并未导出
```

**期待的正常行为**

三四级标题可以正常识别导出。我注意这本书目录中只有一二级标题，但正文中有三四级标题，是因为这个原因导致无法导出三四级标题吗？

**截图**

![image](https://user-images.githubusercontent.com/39029878/148075746-4793eaf5-2d89-4991-9f7d-ba4994271a38.png)

导出缺少1.2.1 三级标题，是因为被算作正文了吗？
![image](https://user-images.githubusercontent.com/39029878/148075702-725c8775-17e7-449e-8921-81eaea3cac6c.png)

**额外信息**

不知道是不是因为三四级标题在正文中出现而目录中没有导致的这个问题，不带小标题导致整理标注比较麻烦，希望能明白这是什么原因

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。是的，扩展一般只能够导出目录中出现的标题。但是可以间接将其他标题导出。

第一种方法是，用单独的标注类型划记你所需要导出而目录中没有的标题，然后在设置中添加前缀。比如，现在需要导出 `1.2.1 ECMAScript` 这个标题，首先，用 `马克笔` 标注它：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/148151965-c56c44ce-68bc-4545-a6f9-1e0ecb2e35b7.png)

</details>

然后，将 `二级标注` 前缀设置为 `### `（注意最后有一个空格）、后缀设置为空（什么也不填），如下：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/148150832-a00830d4-9501-4625-9b87-827f072358f2.png)

</details>

那么 `1.2.1 ECMAScript` 导出来之后，将变成  `### 1.2.1 ECMAScript`。

这种方法要求你用单独的标注来标记内容，也就是说，如果用 `马克笔` 来标注目标标题，那么就不能将它用来标注正文了（因为标注内容导出来之后将被添加你所设置好的前后缀）。

第二种方法是，使用正则表达式。注意到三级标题前面有三个数字标记。比如  `1.2.1 ECMAScript` 中的 `1.2.1 `。借助这一点，可以创建如下正则替换 `s/^([0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2} .*)$/### $1/` 并将其勾选：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/148151735-f1c8649a-b55d-4abb-b9b1-522218384954.png)

</details>

然后标记你所需要导出的标题标记（不需要使用单独的标注类型）：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/148151983-06ef4ad7-e85f-4c10-ba13-ba321bb8f2c4.png)

</details>

之后导出来就会成为  `### 1.2.1 ECMAScript`，四级标题可类似设置。

**Comment by dragon-liu** [comment]
> 

谢谢你的及时回复，我了解是什么情况了，我决定用正则表达式匹配了，这个问题应该解决了，谢谢！
