### ISSUE TITLE
[Feature] 希望设置中能提供一个将想法放在标注后面的选项

### ISSUE THREAD

**Issue by fr0der1c** [Higurashi-kagome/wereader#53]
寻找了一圈发现这个插件好像是唯一支持正确记录各标题的层级的。感谢作者，插件非常实用。

试用了一下发现目前对于包含想法的标注，标注是位于想法后面的。按照我个人的思路的话，应该是先有原文，再有因原文产生的想法，这样比较顺一点。因此希望设置中能提供一个选项，对于包含想法的标注，将想法放在原文后面。

目前效果：
<img width="1052" alt="截屏2022-02-12 下午3 12 08" src="https://user-images.githubusercontent.com/16500161/153701232-c209eed8-6090-4910-ac91-089f461ccc16.png">

期望的效果：
<img width="1052" alt="截屏2022-02-12 下午3 12 33" src="https://user-images.githubusercontent.com/16500161/153701244-bc6a723e-5932-4499-9691-742cd9460cb8.png">

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。想法放在标注之后的确要更合适，其他的选项或许是多余的，所以我将顺序固定了，而没有提供其他选项。新版本 V2.19.27 已送审，不久后将发布到扩展商店。@fr0der1c
