### ISSUE TITLE
[Feature] 增加微读手机端读书圈子的功能

### ISSUE THREAD

**Issue by arry-lee** [Higurashi-kagome/wereader#54]
我是最初的那个[wereader](https://github.com/arry-lee/wereader)的作者，能否利用插件在网页端实现微读手机端读书圈子的功能，官方可能没有这个打算。

**Comment by Higurashi-kagome** [comment]
嗯，我刚抓了一下包，的确有些可以用来创建读书圈子的信息，但这里面的内容相当丰富，加上这段时间事情有些多，可能更新得会比较慢。

**Comment by Higurashi-kagome** [comment]
想了想，觉得这或许已经超出扩展的范围了，所以没有计划实现该功能。
