### ISSUE TITLE
绿色主题时，有白色色块[Bug] 

### ISSUE THREAD

**Issue by mining-id** [Higurashi-kagome/wereader#55]
**设备信息**
扩展版本: [2.19.27] 

**描述问题**
使用绿色主题时，在图书简介和精彩点评的部分，"更多"显示为白色

**出错页面**
全部页面，比如
https://weread.qq.com/web/reader/24632a905aa81d2463cf88b

**截图**
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/94845005/153889119-9bd9cc12-9e62-4142-9504-0133eb7d1351.png">

**Comment by mining-id** [comment]
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/94845005/153889945-6f97061b-5cf3-4e93-867c-df1ee71a7f39.png">

橙色主题也存在该问题

**Comment by Higurashi-kagome** [comment]
嗯，感谢你的使用和反馈。已经基本解决了，因为问题比较小，所以不会马上发布修改后的扩展。
