### ISSUE TITLE
找不到公众号阅读的入口和整理数据的分类管理入口

### ISSUE THREAD

**Issue by ffxung** [Higurashi-kagome/wereader#56]
1. 我看扩展有支持公众号阅读的能力,但找不到. 在我的手机端书架中有添加有公众号, 但pc上找不到.
2. 书籍整理, 没有发现扩展增强了什么能力?  在弹出菜单中的书架类目, 也和手机端的分类不一致. 不清楚是什么原因. 
希望能提供帮助哈~   笔记导出功能很好用,如果全部导出中, 代码和图片也能支持就完美了.

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。

1. 你可以试试进入[书架](https://weread.qq.com/web/shelf)并等待一两秒，不久后应该会出现公众号。或者，你可以点击扩展图标，在扩展弹出的书架菜单中找找，应该也能够找到。
2. 书籍整理也需要进入[书架](https://weread.qq.com/web/shelf)点击“整理书架”才行，网页端微信读书本身是不支持整理书架的。书架类目不正常，可以尝试点击书架旁边的刷新按钮刷新书架看看：
	  <details>
	  <summary>Details</summary>
	  
	  ![image](https://user-images.githubusercontent.com/51501079/154497287-f2ecc50b-96f7-4703-9a5a-74413a567699.png)
	  
	  </details>
3. 早期版本的确支持导出图片和代码，后来微信读书页面改版，实现变得麻烦起来。不过的确有重新实现的计划，但会需要等待一段时间。

**Comment by ffxung** [comment]
1.进入[书架](https://weread.qq.com/web/shelf)并等待一两秒, 还是没看到公众号. 
2. 看到"整理书架"的功能了, 之前以为是原始微信网页端就提供这个功能,没想到是插件提供的. 😓  
书架今天发现完全没有分类了(点击刷新也不行), 其实在手机端书架是有分类目录的:
![image](https://user-images.githubusercontent.com/28615728/154608062-f73e6082-5e9a-4f86-8c88-960d9651e342.png)
书架的类目是拉取的手机端的书架自己建的分类吗?  因为pc端整理书架功能中,也没有找到可以对书籍做分类的功能.

最后, 感谢答复!

**Comment by Higurashi-kagome** [comment]
是的，书架分类也是网页本身不支持的。

我这里扩展能够正常工作，建议你尝试自己检查以提供更多用于定位错误的信息。

一是提前进入扩展管理页面开启“收集错误”选项：

<details>
<summary>进入扩展管理页面</summary>

![image](https://user-images.githubusercontent.com/51501079/141097680-88b01e4e-db02-4ca4-94a5-43e3b5537093.png)

</details>

<details>
<summary>提前开启“收集错误”选项</summary>

![image](https://user-images.githubusercontent.com/51501079/141097797-1a3d0d19-5a2d-4543-a102-0a978a2b8c2a.png)

</details>

然后尝试点击扩展图标打开扩展弹窗，点击书架刷新按钮，不能正常显示则在扩展弹窗上右键单击，点击检查，进入页面控制台，看是否有出现红色的错误打印。

二是在出现不正常工作的状态后，打开扩展背景页，同样检查控制台是否有出现红色的错误打印。

<details>
<summary>打开背景页</summary>

![image](https://user-images.githubusercontent.com/51501079/141097902-f01ada8f-9f99-4637-bcb6-659540622983.png)

</details>

<details>
<summary>进入“控制台”，检查控制台中是否打印有错误</summary>

![image](https://user-images.githubusercontent.com/51501079/141098061-b32d398b-c65e-49cc-987d-44f388a08284.png)

</details>

三是在进入[书架](https://weread.qq.com/web/shelf)后发现没有出现公众号，则按下 F12 在开发者工具的控制台下检查是否有相关错误。

如果打印有错误，请将错误信息复制并反馈给我。如果错误很多不知道哪个是扩展产生的可全部截图反馈。

**Comment by ffxung** [comment]
点击书架的刷新, 控制台出现如下错误:
![image](https://user-images.githubusercontent.com/28615728/154612363-c3c6bb4c-e54d-4ef8-8d51-01830b9ffcd6.png)
在书架页面, 控制台出现如下错误:
![image](https://user-images.githubusercontent.com/28615728/154612733-7dd2476c-fbf8-4e22-befa-3b54a2bec657.png)

**Comment by Higurashi-kagome** [comment]
我对代码进行了简单的完善，并添加了两行打印语句，请将原扩展关掉，然后将[压缩包](https://github.com/Higurashi-kagome/wereader/files/8094088/wereader-chrome.zip)解压，在浏览器中加载解压得到的文件夹并进行测试。如果公众号和书架仍然不能够正常生效，建议将打印得到的两条消息发送给我（不介意书架隐私问题的话）。

**Comment by ffxung** [comment]
用上面最新的压缩包的方式安装插件, 已经解决了书架上公众号不展示的问题和弹出菜单中没有分类问题! 赞效率!
现在关于公众号有一个体验上的问题: 即在书架上, 公众号当前展示在出版物书籍的前面. 因为订阅的公众号数量不少, 自己最近一次在看并置顶的初版书籍也没有办法展示在第一位, 有一点查找上的小小不便.

**Comment by Higurashi-kagome** [comment]
嗯，是的。公众号的放置位置的确可以再完善，顶置书籍也应该显示在最前。我会优先完善该问题，但需要等待一段时间，完善后会随书架问题一起提交并发布新版本。

**Comment by ffxung** [comment]
期待新版本!  感谢~

**Comment by Higurashi-kagome** [comment]
扩展菜单中的书架已支持置顶显示，v2.19.28 不久后将更新到扩展市场。

微信读书官方的读书页没有支持排序（保持原样），因为我有计划将书架管理的功能集成都在扩展菜单上（或许这样要更加简洁方便），到时官方书架页中实现的书架管理和公众号显示功能将会被移除（同时扩展菜单上将会支持），望理解。
