### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by zj1123581321** [Higurashi-kagome/wereader#57]
**请描述目前使用微信读书笔记助手遇到什么不便**

在读英文的书籍时，选中-查询是一个高频的动作。所以希望在现有选中自动点击的基础上加一个『查询』的选项。

**理想情况下，笔记助手应该怎么做**

在 ./options/options.html 里面加一行 <option id="query">查询</option> 即可。

抱歉抱歉，非专业程序员，合并分支这块知识都忘记了...工作的电脑环境都没配==所以直接提 issue 了。。

**额外信息**

![image](https://user-images.githubusercontent.com/33171229/155262032-03484621-82ac-4cb2-953c-4b2137fc0f6b.png)

能否留个赞赏码，聊表支持：)

**Comment by Higurashi-kagome** [comment]
新版本 v2.20.1 不久后将更新到扩展上带你。非常感谢你的慷慨，很高兴能够帮到你 : )。

<details>
<summary>Details</summary>

![微信图片_20220223130234](https://user-images.githubusercontent.com/51501079/155264318-b4f09e6e-e565-43f6-adb4-65f35c6bb71f.jpg)

</details>
