### ISSUE TITLE
[Bug] 导出标注时无法得到图片链接

### ISSUE THREAD

**Issue by Wonderdch** [Higurashi-kagome/wereader#59]
**设备信息**
- 扩展版本: [v2.21.1] 

**描述问题**

导出标注和想法时，图片导出来都只有 [插图] 两个字

**期待的正常行为**

导出后能得到图片链接

**截图**

![image](https://user-images.githubusercontent.com/12708888/156925712-494f86fa-7b59-4d97-964d-3525562532b1.png)
![image](https://user-images.githubusercontent.com/12708888/156925720-0553b6e5-197c-42dc-9929-24530d118a94.png)

**额外信息**

不知道是不支持导出图片链接，还是我的操作有问题

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。扩展之前支持导出图片，后来微信读书改版，出现了导出失败的情况，所以将该功能去掉了。有计划再次支持，但可能需要等等。

**Comment by Wonderdch** [comment]
> 感谢你的使用和反馈。扩展之前支持导出图片，后来微信读书改版，出现了导出失败的情况，所以将该功能去掉了。有计划再次支持，但可能需要等等。

谢谢，辛苦了 😁

**Comment by Higurashi-kagome** [comment]
v2.24.0 支持（在导出本章标注时）附带图片——以一种看起来比较笨拙的方式，不过这是目前我所尝试的最有效的方法了，应该够用。Chrome 通过了，Edge 还在审核。
