### ISSUE TITLE
[Bug] 窗口大小调整后，阅读进度丢失

### ISSUE THREAD

**Issue by mining-id** [Higurashi-kagome/wereader#60]
**设备信息**

扩展版本: [2.21.1] 

**描述问题**

窗口在最大化和半屏之间切换时，阅读进度会跑到当前章节的最后一页

**复现步骤**

有最大化变成半屏，或者半屏变成最大化

任何页面，比如https://weread.qq.com/web/reader/2ec3289071e128722ec7b71

**期待的正常行为**

窗口大小切换时，阅读进度不变

**截图**

<details>
<summary>半屏</summary>

<img width="715" alt="image" src="https://user-images.githubusercontent.com/94845005/157602241-c9144b91-0c7b-44fe-b41b-5e3faacb799b.png">

</details>

<details>
<summary>全屏</summary>

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/94845005/157602163-faea729a-e61f-4471-a371-84a8e232f4e2.png">

</details>

**Comment by Higurashi-kagome** [comment]
我这里似乎没这个问题，不确定是不是扩展导致的。

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/157603354-557b16de-878c-4a58-b864-a7342a3a92e2.gif)

</details>

**Comment by mining-id** [comment]
@Higurashi-kagome  感谢回复，我把其他的扩展禁用了，好像确实不在有这个问题。
抱歉，误报了，下次注意。
