### ISSUE TITLE
请问如何统计周/月阅读时间？ 

### ISSUE THREAD

**Issue by pxsongchn** [Higurashi-kagome/wereader#63]
如题，谢谢！

**Comment by Higurashi-kagome** [comment]
右键扩展图标，点击”扩展选项“进入选项页，在“其他”中选中“开启统计”：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/160216598-aefd1916-1a1c-4127-9725-8a5632015125.png)

</details>

之后扩展弹窗中就会出现”统计“：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/160216634-9c7e64d5-8f4c-4b3d-bab5-d05d50db7419.png)

</details>

点击进入统计页面。比较初级，仅仅是显示了两条曲线。

**Comment by pxsongchn** [comment]
感谢！
