### ISSUE TITLE
[Feature] 提供同步到语雀功能

### ISSUE THREAD

**Issue by jiangtao** [Higurashi-kagome/wereader#64]
RT.

**Comment by Higurashi-kagome** [comment]
嗯，的确可以考虑直接导出到类似的软件，只是现在来说，不会优先支持这些功能（而且也不确定之后是否会支持）。

一方面是因为目前的一些已存功能还不够完善，我希望能先将扩展的基础功能做好，再考虑添加更多的特性；另外，直接将导出的文本粘贴到语雀也是可行的（虽然可能多少还是有点麻烦），所以看来似乎并不是十分有帮助。望理解。
