### ISSUE TITLE
获取本章注释失败[Bug] 

### ISSUE THREAD

**Issue by HWA2022** [Higurashi-kagome/wereader#66]
**设备信息**
- 扩展版本: [2.24.0] 

**描述问题**
为获取图片注释，选择获取本章注释，结果没有反应，但能成功获取全部注释，没有图片注释，只显示[插图]。

**复现步骤**

**期待的正常行为**
导出文字和图片注释

**截图**

1. 选择获取本章注释 ，结果不能成功获取
![image](https://user-images.githubusercontent.com/100739848/161968677-bcf9dadc-468d-499a-b37a-3cc284ff0eb2.png)
 
2. 选择获取全部注释，结果成功获取，显示复制成功
![image](https://user-images.githubusercontent.com/100739848/161968935-82fb71d2-8bca-49cc-8441-4f4aab79d6be.png)

3. 获取成功
![image](https://user-images.githubusercontent.com/100739848/161969013-21ed4007-f6a2-486c-9db4-7b06aa2c28c8.png)

**额外信息**

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。因为没有反应，所以需要从控制台获取更多信息。

第一步：右击扩展，进入扩展管理页面，开启错误信息收集。

<details>
<summary>进入扩展管理页面</summary>

![image](https://user-images.githubusercontent.com/51501079/141097680-88b01e4e-db02-4ca4-94a5-43e3b5537093.png)

</details>

<details>
<summary>开启“收集错误”选项</summary>

![image](https://user-images.githubusercontent.com/51501079/141097797-1a3d0d19-5a2d-4543-a102-0a978a2b8c2a.png)

</details>

第二步：刷新读书页，尝试导出本章标注，如果失败，在读书页按下 F12，点击控制台，检查是否有红色文字（报错信息）。

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/161971936-0b42ed3a-cd0b-4648-a67d-cd5bb34f09b0.png)

</details>

第三步：进入进入背景页，点击控制台，检查是否有红色文字（报错信息）。

<details>
<summary>打开背景页</summary>

![image](https://user-images.githubusercontent.com/51501079/141097902-f01ada8f-9f99-4637-bcb6-659540622983.png)

</details>

<details>
<summary>检查控制台</summary>

![image](https://user-images.githubusercontent.com/51501079/161971655-e6df38e8-7e43-4aa4-955b-f500c9667165.png)

</details>

麻烦将找到的任何红色文字（报错信息）反馈给我。

**Comment by Higurashi-kagome** [comment]
已发现一个可能的问题。新版本（v2.24.1）正在审核，通过后可以试试。

**Comment by Higurashi-kagome** [comment]
最新版本 （v2.24.2）应该已将问题解决。已更新到 Chrome 扩展商店，Edge 正在审核。有新的问题可重新反馈。
