### ISSUE TITLE
[Bug] 公众号疑似改了接口，无法显示了

### ISSUE THREAD

**Issue by moleng09** [Higurashi-kagome/wereader#69]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/54031747/165298570-4e9d49d8-3ea4-499b-942d-2f9d4f34430a.png">
<img width="153" alt="image" src="https://user-images.githubusercontent.com/54031747/165298727-5c246012-53c5-4ee7-8ba7-6b50413309e7.png">

**Comment by Higurashi-kagome** [comment]
我这边是可以的。建议右键书架弹窗检查以下，看看控制台是不是有报错信息。

**Comment by alynx00** [comment]
我也遇到了, 补充下错误信息
shelf:28 
 Error handling response: TypeError: Cannot read properties of undefined (reading 'normal')
    at getConfig (chrome-extension://cbopgngpbfeoecnbebghbbhmdadmllce/js/event.js:1750:60)
    at Object.constinit (chrome-extension://cbopgngpbfeoecnbebghbbhmdadmllce/js/event.js:131:28)
    at chrome-extension://cbopgngpbfeoecnbebghbbhmdadmllce/js/event.js:1852:9
shelf:28 
 Unchecked runtime.lastError: The message port closed before a response was received.
shelf:28 
 Error handling response: TypeError: Cannot read properties of undefined (reading 'shouldShowReminderOnboarding')
    at chrome-extension://cbopgngpbfeoecnbebghbbhmdadmllce/js/event.js:2191:26
shelf:28 
 Unchecked runtime.lastError: The message port closed before a response was received.
shelf:1

**Comment by Higurashi-kagome** [comment]
不知出问题的扩展是否为最新版本？@alynx00
