### ISSUE TITLE
关于标注和想法先后顺序的建议

### ISSUE THREAD

**Issue by protea-ban** [Higurashi-kagome/wereader#72]
首先，感谢作者为我们提供了这么好用的插件。

### 问题描述

我原本是想用**学习骇客**提供的微信读书笔记转 Anki 模板，才开始找导出插件的，[模板](https://hintsnet.com/tools/wxread2roam/index.html)大致如下：
![image](https://user-images.githubusercontent.com/27531141/169491716-6e7e5d09-0a74-4971-8324-12cb74999113.png)

最终找到了这个插件做的最好，作者也在持续改进。**现在问题是 Leo 提供的模板里，标注是在笔记后面的，而该插件的导出格式是标注在笔记前面**，这点能不能改一下？或者提供个更改选项？

### 更好点

更好点，升个级，把导出格式改成非常符合 Anki 导入模板的形式，如下面这种
```
卡片笔记写作法：如何实现从阅读到写作
申克·阿伦斯
166个笔记

◆ 中文版序

问题1：bla bla bla
答案1：bla bla bla
补充1：文字 文字 文字
>> 引用文字1

问题2：bla bla bla
答案2：bla bla bla
补充2：文字 文字 文字
>> 引用文字3

问题3：bla bla bla
答案3：bla bla bla
补充3：文字 文字 文字
>> 引用文字3

卡片笔记写作法：如何实现从阅读到写作
申克·阿伦斯
166个笔记

◆ 新的一章

问题1：bla bla bla
答案1：bla bla bla
补充1：文字 文字 文字
>> 引用文字1

问题2：bla bla bla
答案2：bla bla bla
补充2：文字 文字 文字
>> 引用文字3

问题3：bla bla bla
答案3：bla bla bla
补充3：文字 文字 文字
>> 引用文字3
```
### 最最好点

最最好点，能直接实现导出 Roam 格式，我看 Leo 那网站里使用 JS 语言实现的，脚本也能拿到，我都想自己搞搞试试，可 Python 我还行，JS 是真看不懂。

最后贴上 Leo 的 Anki 模板链接：
[微信读书笔记转换为 Roam 粘贴格式 | 在线格式转换工具 | 引思网 (hintsnet.com)](https://hintsnet.com/tools/wxread2roam/index.html)
[自动化系列：如何把微信读书的笔记转入ANKI回顾？| 学习骇客 (qq.com)](https://mp.weixin.qq.com/s?__biz=MzU2NDI1Mzg2NQ==&mid=2247489786&idx=1&sn=5f547130736b428ef9ad9863b812b1c5&chksm=fc4c9d3ccb3b142af666b942bc55276fb767defd9d91a6a92ee259b461c982332c3dcb37aa11&scene=21#wechat_redirect)

**Comment by Higurashi-kagome** [comment]
设置想法导出顺序的功能将会支持（可能会明天发布），可能以后会支持导出“书籍和作者信息”，现在还不太确定。

似乎是可以自己配置成 Roam 格式的。标题、标注、想法都可以设置前后缀，比如给标题添加 `◆ ` 前缀，不知道行不行。@protea-ban

**Comment by protea-ban** [comment]
大赞作者的更新速度！

我立马试了试，发现了一个算是小 bug ？

设置「想法在标注之前」，通过「获取我的想法」，确实标注在后，但这样导出了全部的想法，于是我试了试「获取标注--本章」，发现这样导出的内容里，标注出现了两次，通过获取我的想法导出的内容不会，如下图，不知是本来就这样的设定，还是出现了 bug 。

![image](https://user-images.githubusercontent.com/27531141/169674327-6f20f8ec-0a80-438f-b633-8ddd02a17731.png)
![image](https://user-images.githubusercontent.com/27531141/169674372-f5f53e33-dbe5-4d41-812b-2725e0a1b2fc.png)

再次感谢作者！

**Comment by Higurashi-kagome** [comment]
这大概是因为想法所对应的标注同时被“直线/马克笔/波浪线”标记了，插件先导出被“直线/马克笔/波浪线”标记的文字，然后添加想法，添加想法时又附加了一次想法所对应的标注，所以同一段文本出现了两次：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/169675816-dbc3115f-b21b-4461-9a88-9723da9a0701.png)

</details>

单独获取想法时，插件不会尝试导出标注，只会出现想法及其对应的文字，不会出现内容重复。

之后应该会支持设置是否保留重复文本。

**Comment by protea-ban** [comment]
明白了，那获取我的想法功能，后续会增加只导出本章想法的功能吗？

**Comment by Higurashi-kagome** [comment]
是的，有这个计划，应该会和处理重复文本的功能一起出现在下一个版本中。

**Comment by protea-ban** [comment]
好的，感谢作者。

**Comment by protea-ban** [comment]
刚刚试了试 完美 👍
