### ISSUE TITLE
[Bug] 提示网页版不支持公众号

### ISSUE THREAD

**Issue by andrewrong** [Higurashi-kagome/wereader#73]
**扩展是否为最新版本（与[扩展商店](https://chrome.google.com/webstore/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/cmlenojlebcodibpdhmklglnbaghpdcg?hl=zh-CN&authuser=0)中的版本相同）**

- [x] 是

**出现该问题的书本及章节（不方便公开的话可直接发[邮箱](mailto:higurashi-kagome@qq.com)告知）**
点击书架上的订阅的公众号

**描述问题**
之前在书架上订阅了公众号，都还能看；今天打开的时候发现会提示这样的标语:
![image](https://user-images.githubusercontent.com/1272833/172748072-617e9213-1b32-4f34-a9d1-ae8a2d39c2cb.png)

**复现步骤**
其实只需要点击一下书架上，管理的公众号，就会跳出一句话：公众号不支持网页版本

**期待的正常行为**
之前使用本插件的时候是可以看的？以后是否还支持？

**截图**
![image](https://user-images.githubusercontent.com/1272833/172748072-617e9213-1b32-4f34-a9d1-ae8a2d39c2cb.png)

**额外信息**

**Comment by Higurashi-kagome** [comment]
我这边没能复现问题：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/172749593-4abaa7c7-447a-49a7-8068-e8f4d1c736e0.png)

</details>

不确定这个提示是在哪个页面出现的。

有一种可能是频繁的公众号操作触发了反爬机制，可以隔一段时间再看看能不能恢复。或者是提供更详细的信息，方便定位问题。

**Comment by Higurashi-kagome** [comment]
我这边没能复现问题：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/172749593-4abaa7c7-447a-49a7-8068-e8f4d1c736e0.png)

</details>

或许你是尝试从 https://weread.qq.com/web/shelf 进入公众号？扩展不支持从这里进入，需要点击扩展图标，弹出的小窗口中有“书架”，书架中的公众号应该是可以正确跳转的：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/172750831-ab940575-f514-468d-a113-1724201d1c6d.png)

</details>

**Comment by andrewrong** [comment]
谢谢你那么及时回复；我也不知道我为什么就不大行；我给你截个图看看
![image](https://user-images.githubusercontent.com/1272833/172751210-b1754682-ad32-45ff-99cf-44d4c4b261f4.png)

这个界面是从你上面给我的url里面点击进去的;

**Comment by andrewrong** [comment]
不好意思不好意思，的确从插件点击进去就可以了；
