### ISSUE TITLE
[Feature] 希望能增加自动生成 markdown 文件，下载到本地的特定路径

### ISSUE THREAD

**Issue by qiuqianyuanluo** [Higurashi-kagome/wereader#75]
**请描述目前使用微信读书笔记助手遇到什么不便**

需要手动创建 Markdown 文档黏贴，不能直接存放进 Logseq/Obsidian 的文库

**理想情况下，笔记助手应该怎么做**

点击插件后选择全部导出，生成一个可以下载的 markdown 文件，根据提前设置好的路径下载下来。
这样，等有空编辑了，打开笔记软件后，文件已经在那里了。

**额外信息**

感谢！！这样真的很酷
很缺乏可以自动导出笔记且功能 OK 的 Epub 阅读器，微信读书目测是最好的选项

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈。总的来说我感觉粘贴并不是很麻烦...可能暂时不会支持该功能。我也用微信读书导入过 Epub，在我正感觉好用之时，发现某些横排的文字变成了竖排，可能是因为那本书比较特殊吧。
