### ISSUE TITLE
提示未在chrome商店上架，无法开启插件[Bug] 

### ISSUE THREAD

**Issue by lurenf11** [Higurashi-kagome/wereader#80]
**扩展是否为最新版本（与[扩展商店](https://chrome.google.com/webstore/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/cmlenojlebcodibpdhmklglnbaghpdcg?hl=zh-CN&authuser=0)中的版本相同）**

- [x] 是

**出现该问题的书本及章节（不方便公开的话可直接发[邮箱](mailto:higurashi-kagome@qq.com)告知）**

**描述问题**

**复现步骤**

安装后无法开启，提示插件未在chrome商店上架

**期待的正常行为**

如何开启？
**截图**

![企业微信截图_16589969042523](https://user-images.githubusercontent.com/47886369/181460086-5a52fea0-82f6-4462-8559-e7984218753b.png)

**额外信息**

**Comment by Higurashi-kagome** [comment]
的确有这个问题。已更新 [README](https://github.com/Higurashi-kagome/wereader/blob/master/README.md)，可按步骤通过解压 zip 文件安装。 @lurenf11
