### ISSUE TITLE
[Bug] 书架无法加载

### ISSUE THREAD

**Issue by bighaidao** [Higurashi-kagome/wereader#86]
书架无法加载

**扩展是否为最新版本（与[扩展商店](https://chrome.google.com/webstore/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/cmlenojlebcodibpdhmklglnbaghpdcg?hl=zh-CN&authuser=0)中的版本相同）**

- [ ] 是

**出现该问题的书本及章节（不方便公开的话可直接发[邮箱](mailto:higurashi-kagome@qq.com)告知）**

**描述问题**

**复现步骤**

**期待的正常行为**

**截图**

**额外信息**

微信公众号无法通过插件打开了， 麻烦看看
![image](https://user-images.githubusercontent.com/1301460/210769857-c93394e8-beb2-4150-97fb-f9dea1786f29.png)

书架无法加载

**Comment by Higurashi-kagome** [comment]
书架加载需要登录微信读书网页端，登录后还是加载不出吗？

**Comment by bighaidao** [comment]
我是 chrome， 按照你的逻辑，确实有报错。 

![image](https://user-images.githubusercontent.com/1301460/212219944-7ec56817-3b9d-4b9e-8452-7dd119875e7e.png)

**Comment by bighaidao** [comment]
我用edge 好像也是同样的问题。 
![image](https://user-images.githubusercontent.com/1301460/212229684-f386e68c-e829-4331-9b28-8eb305ba932c.png)

**Comment by Higurashi-kagome** [comment]
嗯，好，我晚些检查一下。

**Comment by Higurashi-kagome** [comment]
虽然暂时不知道具体是什么情况会出错，但加了一点判断之后，应该就不存在这个问题了，暂时不会发布修复版本，可以先试试打包好的[离线版](https://github.com/Higurashi-kagome/wereader/files/10412205/dist.zip)。安装方式可参考 #88。

**Comment by bighaidao** [comment]
> 虽然暂时不知道具体是什么情况下会出错，但加了一点判断之后，应该就不存在这个问题了，暂时不会发布修复版本，可以先试试打包好的[离线版](https://github.com/Higurashi-kagome/wereader/files/10412205/dist.zip)。安装方式可参考 #88。

按照新版本可以了。 感谢！
