### ISSUE TITLE
没有找到可以同时导出自己想法和标注的功能

### ISSUE THREAD

**Issue by 134df8c** [Higurashi-kagome/wereader#94]
没有找到可以同时导出自己想法和标注的功能

**Comment by Higurashi-kagome** [comment]
可以看看这里是不是开启了：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/229964984-7e3c5edb-58a1-4506-97d2-0eafe42a0ed2.png)

</details>

**Comment by taididibear** [comment]
谢谢，可以了
