### ISSUE TITLE
选择文本自动复制功能，选两次，才成功一次

### ISSUE THREAD

**Issue by 478959472** [Higurashi-kagome/wereader#96]
选择文本自动复制功能，选两次，才成功一次
注释下面代码后正常
src/content/modules/content-hide.ts
reader_toolbar.remove()

**Comment by 76563** [comment]
同样的，我是昨天#95号bug的反馈者，虽然现在框没了，但也是选两次才能成功一次

**Comment by Higurashi-kagome** [comment]
确实有这个问题，今天将会更新，应该可以了。
