### ISSUE TITLE
[Bug] 标注中的插图顺序不正确

### ISSUE THREAD

**Issue by beanliu** [Higurashi-kagome/wereader#99]
**扩展是否为最新版本（与[扩展商店](https://chrome.google.com/webstore/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E5%8A%A9%E6%89%8B/cmlenojlebcodibpdhmklglnbaghpdcg?hl=zh-CN&authuser=0)中的版本相同）**

- [x] 是 (Chrome 2.25.15)

**出现该问题的书本及章节（不方便公开的话可直接发[邮箱](mailto:higurashi-kagome@qq.com)告知）**

[贝叶斯的博弈](https://weread.qq.com/web/bookDetail/de232b6072359c0ade2d48f)

**描述问题**

导出标注时，若文字中包含多个插图，那么在导出结果中，这些插图的顺序可能是乱的。

比如下面这一段：
<img width="829" alt="image" src="https://github.com/Higurashi-kagome/wereader/assets/846049/7a05a0be-4834-4b59-95f7-ce9329f48b01">

导出后插图的顺序不一致：
<img width="665" alt="image" src="https://github.com/Higurashi-kagome/wereader/assets/846049/b14f2f91-9a38-4e50-b96e-75785a6909b8">

**复现步骤**

在上述书籍中，随意标注一段带多个插图的文字，然后导出本章标注。

**额外信息**

阅读了下相关代码（`getMarkedData`），处理逻辑是对于每一个标注，都遍历一下当前可见的所有插图，找出与当前标注覆盖重合的子集，并按照查找到的顺序添加到 `markedData` 中。猜测问题是这里的查找到的顺序与实际阅读顺序并不一致，稍微修改了下按其 `getBoundingClientRect` 左上顶角排序，本地测试可以解决我遇到的case。

**Comment by Higurashi-kagome** [comment]
感谢反馈，所提供的信息很有帮助。
